In [1]:
import re 
import pandas as pd
from collections import Counter

In [2]:
df = pd.read_csv("/Users/kaitaoyang/Downloads/datasets_conversations/DailyDialog/train.csv")
print(df.shape)
df.head(2)

(11118, 3)

,dialog,act,emotion
0,"['Say , Jim , how about going for a few beers ...",[3 4 2 2 2 3 4 1 3 4],[0 0 0 0 0 0 4 4 4 4]
1,"['Can you do push-ups ? '\n "" Of course I can ...",[2 1 2 2 1 1],[0 0 6 0 0 0]

In [3]:
text_raw = " ".join(df.dialog.to_list()).lower()
text_clean_list = re.findall(r"[a-zA-Z\-]+", text_raw)
text_clean_list[:100]

['say',
 'jim',
 'how',
 'about',
 'going',
 'for',
 'a',
 'few',
 'beers',
 'after',
 'dinner',
 'you',
 'know',
 'that',
 'is',
 'tempting',
 'but',
 'is',
 'really',
 'not',
 'good',
 'for',
 'our',
 'fitness',
 'what',
 'do',
 'you',
 'mean',
 'it',
 'will',
 'help',
 'us',
 'to',
 'relax',
 'do',
 'you',
 'really',
 'think',
 'so',
 'i',
 'don',
 't',
 'it',
 'will',
 'just',
 'make',
 'us',
 'fat',
 'and',
 'act',
 'silly',
 'remember',
 'last',
 'time',
 'i',
 'guess',
 'you',
 'are',
 'right',
 'but',
 'what',
 'shall',
 'we',
 'do',
 'i',
 'don',
 't',
 'feel',
 'like',
 'sitting',
 'at',
 'home',
 'i',
 'suggest',
 'a',
 'walk',
 'over',
 'to',
 'the',
 'gym',
 'where',
 'we',
 'can',
 'play',
 'singsong',
 'and',
 'meet',
 'some',
 'of',
 'our',
 'friends',
 'that',
 's',
 'a',
 'good',
 'idea',
 'i',
 'hear',
 'mary',
 'and']

In [4]:
len(set(text_clean_list))

18087

In [5]:
word_counter = Counter(text_clean_list)
word_counter.most_common(1000)

[('i', 45725),
 ('you', 40986),
 ('the', 32365),
 ('to', 27771),
 ('a', 23508),
 ('it', 20392),
 ('s', 15641),
 ('and', 14345),
 ('is', 13811),
 ('that', 13615),
 ('of', 11651),
 ('in', 11116),
 ('have', 10893),
 ('for', 10542),
 ('t', 10458),
 ('do', 9287),
 ('what', 9038),
 ('can', 8528),
 ('are', 8526),
 ('we', 8342),
 ('your', 7899),
 ('my', 7191),
 ('me', 7120),
 ('be', 6480),
 ('this', 6411),
 ('like', 6094),
 ('but', 6031),
 ('on', 6030),
 ('m', 5832),
 ('with', 5312),
 ('yes', 5290),
 ('how', 5212),
 ('so', 5053),
 ('about', 4617),
 ('will', 4612),
 ('there', 4608),
 ('don', 4598),
 ('at', 4239),
 ('ll', 4197),
 ('not', 4077),
 ('think', 4008),
 ('well', 3969),
 ('good', 3888),
 ('no', 3873),
 ('know', 3749),
 ('all', 3676),
 ('get', 3616),
 ('just', 3609),
 ('here', 3604),
 ('would', 3569),
 ('they', 3499),
 ('if', 3428),
 ('go', 3368),
 ('he', 3301),
 ('was', 3270),
 ('see', 3155),
 ('one', 3144),
 ('right', 3115),
 ('very', 3075),
 ('really', 3071),
 ('some', 2956),
 ('want', 2822),
 ('time', 2821),
 ('please', 2730),
 ('oh', 2606),
 ('as', 2525),
 ('ve', 2521),
 ('much', 2469),
 ('our', 2428),
 ('take', 2428),
 ('re', 2397),
 ('now', 2375),
 ('too', 2364),
 ('going', 2359),
 ('need', 2323),
 ('up', 2289),
 ('an', 2282),
 ('out', 2270),
 ('let', 2233),
 ('am', 2227),
 ('sure', 2219),
 ('ok', 2205),
 ('from', 2204),
 ('when', 2183),
 ('or', 2155),
 ('thank', 2124),
 ('she', 2085),
 ('did', 2080),
 ('d', 2008),
 ('could', 1978),
 ('then', 1964),
 ('should', 1915),
 ('why', 1830),
 ('more', 1810),
 ('help', 1806),
 ('any', 1709),
 ('them', 1695),
 ('been', 1683),
 ('got', 1666),
 ('work', 1666),
 ('by', 1659),
 ('make', 1639),
 ('come', 1631),
 ('look', 1627),
 ('new', 1568),
 ('great', 1507),
 ('people', 1477),
 ('where', 1417),
 ('her', 1385),
 ('has', 1381),
 ('thanks', 1341),
 ('tell', 1318),
 ('sir', 1299),
 ('sorry', 1285),
 ('day', 1266),
 ('may', 1250),
 ('first', 1229),
 ('had', 1220),
 ('lot', 1215),
 ('way', 1169),
 ('yeah', 1160),
 ('give', 1160),
 ('today', 1151),
 ('us', 1145),
 ('only', 1129),
 ('many', 1122),
 ('two', 1122),
 ('back', 1114),
 ('over', 1104),
 ('anything', 1101),
 ('him', 1084),
 ('something', 1075),
 ('company', 1067),
 ('long', 1052),
 ('next', 1029),
 ('room', 1016),
 ('job', 1016),
 ('other', 1009),
 ('didn', 1007),
 ('course', 1001),
 ('say', 989),
 ('last', 985),
 ('also', 982),
 ('morning', 966),
 ('nice', 963),
 ('better', 961),
 ('problem', 956),
 ('does', 950),
 ('mr', 930),
 ('were', 915),
 ('who', 912),
 ('his', 911),
 ('find', 898),
 ('after', 888),
 ('try', 870),
 ('than', 864),
 ('before', 858),
 ('little', 856),
 ('must', 846),
 ('fine', 846),
 ('kind', 844),
 ('these', 838),
 ('money', 835),
 ('maybe', 833),
 ('which', 827),
 ('always', 822),
 ('buy', 801),
 ('hello', 798),
 ('pay', 791),
 ('call', 788),
 ('things', 781),
 ('because', 772),
 ('love', 767),
 ('tomorrow', 751),
 ('week', 748),
 ('use', 745),
 ('name', 743),
 ('most', 741),
 ('feel', 733),
 ('down', 726),
 ('sounds', 720),
 ('still', 717),
 ('check', 716),
 ('off', 707),
 ('again', 705),
 ('hi', 699),
 ('never', 695),
 ('their', 686),
 ('year', 678),
 ('home', 676),
 ('mean', 675),
 ('idea', 675),
 ('put', 673),
 ('days', 668),
 ('few', 666),
 ('doing', 657),
 ('into', 649),
 ('hope', 643),
 ('best', 635),
 ('isn', 632),
 ('won', 616),
 ('ask', 615),
 ('night', 613),
 ('quite', 612),
 ('food', 608),
 ('around', 606),
 ('three', 599),
 ('office', 598),
 ('mind', 588),
 ('years', 585),
 ('car', 585),
 ('else', 580),
 ('bad', 580),
 ('okay', 576),
 ('working', 574),
 ('every', 568),
 ('afraid', 566),
 ('looking', 560),
 ('keep', 560),
 ('business', 560),
 ('school', 557),
 ('hard', 556),
 ('excuse', 554),
 ('even', 549),
 ('actually', 547),
 ('everything', 545),
 ('english', 544),
 ('order', 536),
 ('doesn', 532),
 ('big', 531),
 ('another', 531),
 ('made', 527),
 ('meet', 526),
 ('card', 523),
 ('number', 523),
 ('haven', 514),
 ('place', 512),
 ('soon', 510),
 ('wait', 507),
 ('same', 505),
 ('thing', 503),
 ('each', 503),
 ('said', 500),
 ('house', 498),
 ('month', 494),
 ('afternoon', 491),
 ('thought', 491),
 ('those', 486),
 ('chinese', 486),
 ('such', 483),
 ('show', 480),
 ('dollars', 477),
 ('change', 477),
 ('price', 475),
 ('heard', 471),
 ('hear', 469),
 ('minutes', 469),
 ('guess', 467),
 ('might', 467),
 ('usually', 466),
 ('welcome', 465),
 ('old', 460),
 ('done', 458),
 ('leave', 458),
 ('start', 457),
 ('bus', 457),
 ('while', 456),
 ('happy', 453),
 ('pretty', 449),
 ('getting', 449),
 ('believe', 444),
 ('class', 442),
 ('certainly', 441),
 ('tonight', 441),
 ('already', 441),
 ('yet', 439),
 ('enough', 438),
 ('looks', 437),
 ('eat', 428),
 ('play', 424),
 ('dinner', 422),
 ('different', 422),
 ('hey', 417),
 ('bit', 414),
 ('later', 412),
 ('miss', 412),
 ('city', 412),
 ('bring', 410),
 ('ready', 406),
 ('stay', 405),
 ('nothing', 404),
 ('late', 401),
 ('friends', 400),
 ('talk', 397),
 ('worry', 394),
 ('coming', 391),
 ('remember', 387),
 ('wrong', 387),
 ('away', 387),
 ('important', 386),
 ('used', 385),
 ('party', 379),
 ('often', 378),
 ('family', 378),
 ('phone', 378),
 ('-', 377),
 ('ever', 376),
 ('through', 376),
 ('account', 373),
 ('computer', 369),
 ('enjoy', 367),
 ('meeting', 365),
 ('drink', 363),
 ('service', 363),
 ('evening', 360),
 ('left', 357),
 ('beautiful', 354),
 ('glad', 354),
 ('true', 351),
 ('five', 350),
 ('seems', 349),
 ('easy', 348),
 ('someone', 347),
 ('live', 342),
 ('high', 341),
 ('stop', 339),
 ('care', 339),
 ('having', 339),
 ('moment', 339),
 ('world', 336),
 ('country', 332),
 ('understand', 332),
 ('small', 331),
 ('china', 331),
 ('yuan', 331),
 ('free', 330),
 ('life', 327),
 ('watch', 327),
 ('together', 327),
 ('send', 327),
 ('both', 326),
 ('went', 325),
 ('told', 324),
 ('interested', 324),
 ('interesting', 323),
 ('able', 322),
 ('wow', 322),
 ('speak', 322),
 ('probably', 322),
 ('offer', 322),
 ('yourself', 320),
 ('friend', 320),
 ('hours', 317),
 ('far', 316),
 ('coffee', 315),
 ('information', 315),
 ('turn', 314),
 ('sometimes', 313),
 ('own', 308),
 ('movie', 308),
 ('weekend', 307),
 ('special', 307),
 ('prefer', 306),
 ('being', 306),
 ('myself', 305),
 ('book', 305),
 ('until', 304),
 ('o', 304),
 ('fun', 301),
 ('hotel', 299),
 ('man', 298),
 ('music', 297),
 ('bank', 297),
 ('shall', 296),
 ('open', 296),
 ('thinking', 293),
 ('yesterday', 292),
 ('busy', 292),
 ('read', 292),
 ('expensive', 291),
 ('once', 290),
 ('mary', 289),
 ('set', 288),
 ('hour', 288),
 ('everyone', 288),
 ('doctor', 285),
 ('sign', 281),
 ('ten', 281),
 ('almost', 281),
 ('seen', 279),
 ('bill', 278),
 ('ticket', 277),
 ('exactly', 276),
 ('charge', 276),
 ('credit', 275),
 ('plan', 274),
 ('matter', 274),
 ('since', 272),
 ('manager', 272),
 ('experience', 271),
 ('fill', 271),
 ('apartment', 270),
 ('agree', 268),
 ('four', 267),
 ('several', 266),
 ('though', 266),
 ('wife', 266),
 ('restaurant', 266),
 ('clock', 265),
 ('possible', 264),
 ('water', 264),
 ('called', 264),
 ('department', 264),
 ('hot', 263),
 ('happened', 263),
 ('flight', 262),
 ('cost', 261),
 ('ago', 261),
 ('weather', 261),
 ('parents', 260),
 ('learn', 258),
 ('trip', 258),
 ('second', 256),
 ('anyway', 255),
 ('cold', 254),
 ('university', 254),
 ('times', 253),
 ('aren', 253),
 ('table', 253),
 ('position', 252),
 ('wish', 252),
 ('boss', 252),
 ('form', 250),
 ('walk', 249),
 ('end', 248),
 ('taking', 247),
 ('tv', 247),
 ('cash', 246),
 ('weeks', 245),
 ('john', 244),
 ('half', 244),
 ('bought', 243),
 ('pick', 242),
 ('street', 242),
 ('spend', 241),
 ('person', 240),
 ('perfect', 238),
 ('birthday', 237),
 ('clothes', 237),
 ('move', 235),
 ('lost', 235),
 ('makes', 234),
 ('interview', 234),
 ('case', 233),
 ('calling', 233),
 ('rather', 232),
 ('minute', 230),
 ('seat', 230),
 ('found', 230),
 ('wanted', 230),
 ('smith', 228),
 ('wonderful', 227),
 ('mom', 227),
 ('part', 227),
 ('friday', 226),
 ('alright', 225),
 ('date', 224),
 ('large', 224),
 ('news', 224),
 ('couldn', 224),
 ('visit', 223),
 ('talking', 222),
 ('married', 222),
 ('write', 222),
 ('saw', 221),
 ('early', 219),
 ('air', 219),
 ('months', 218),
 ('available', 218),
 ('comes', 217),
 ('line', 217),
 ('wouldn', 216),
 ('making', 215),
 ('tom', 215),
 ('started', 214),
 ('children', 214),
 ('internet', 214),
 ('summer', 212),
 ('reservation', 212),
 ('forget', 211),
 ('real', 211),
 ('beijing', 210),
 ('trying', 209),
 ('under', 208),
 ('shopping', 208),
 ('white', 207),
 ('six', 207),
 ('size', 207),
 ('train', 207),
 ('market', 206),
 ('without', 206),
 ('during', 206),
 ('favorite', 205),
 ('choose', 205),
 ('lunch', 204),
 ('deposit', 204),
 ('th', 203),
 ('run', 203),
 ('along', 203),
 ('red', 203),
 ('living', 202),
 ('game', 202),
 ('drive', 202),
 ('serious', 202),
 ('problems', 202),
 ('hair', 202),
 ('whole', 201),
 ('its', 201),
 ('products', 201),
 ('least', 201),
 ('study', 200),
 ('says', 200),
 ('wasn', 200),
 ('deal', 200),
 ('took', 200),
 ('perhaps', 199),
 ('pleasure', 199),
 ('team', 198),
 ('came', 198),
 ('seem', 198),
 ('madam', 197),
 ('tea', 197),
 ('girl', 196),
 ('wear', 196),
 ('books', 196),
 ('sit', 194),
 ('chance', 192),
 ('paper', 192),
 ('cut', 192),
 ('hold', 192),
 ('bye', 191),
 ('either', 190),
 ('couple', 190),
 ('teacher', 188),
 ('speaking', 188),
 ('excellent', 187),
 ('rest', 187),
 ('appreciate', 187),
 ('hand', 185),
 ('trouble', 185),
 ('tired', 185),
 ('rent', 185),
 ('exercise', 184),
 ('feeling', 184),
 ('college', 184),
 ('appointment', 184),
 ('difficult', 183),
 ('park', 183),
 ('saturday', 183),
 ('sales', 182),
 ('cool', 180),
 ('full', 180),
 ('guy', 179),
 ('black', 178),
 ('wonder', 177),
 ('insurance', 177),
 ('especially', 177),
 ('short', 176),
 ('worked', 175),
 ('waiting', 175),
 ('store', 174),
 ('tried', 174),
 ('supposed', 174),
 ('color', 174),
 ('questions', 174),
 ('recommend', 174),
 ('letter', 173),
 ('terrible', 173),
 ('decided', 173),
 ('salary', 173),
 ('return', 172),
 ('seven', 172),
 ('means', 172),
 ('vacation', 171),
 ('needs', 171),
 ('husband', 170),
 ('mother', 167),
 ('asked', 167),
 ('contract', 167),
 ('list', 166),
 ('suit', 166),
 ('young', 165),
 ('wine', 165),
 ('dance', 164),
 ('american', 164),
 ('question', 164),
 ('extra', 164),
 ('traffic', 163),
 ('forward', 163),
 ('lose', 163),
 ('top', 163),
 ('finished', 163),
 ('hate', 162),
 ('besides', 162),
 ('near', 162),
 ('popular', 162),
 ('between', 162),
 ('pass', 162),
 ('outside', 162),
 ('rate', 162),
 ('listen', 161),
 ('face', 161),
 ('sleep', 161),
 ('floor', 161),
 ('kids', 160),
 ('suppose', 160),
 ('chicken', 159),
 ('absolutely', 159),
 ('hundred', 158),
 ('mine', 158),
 ('per', 158),
 ('dress', 157),
 ('catch', 157),
 ('travel', 157),
 ('sick', 156),
 ('winter', 156),
 ('side', 155),
 ('dad', 155),
 ('ones', 155),
 ('green', 155),
 ('machine', 155),
 ('luck', 155),
 ('ahead', 155),
 ('definitely', 154),
 ('finish', 154),
 ('single', 154),
 ('paid', 154),
 ('reading', 153),
 ('major', 152),
 ('thirty', 151),
 ('father', 151),
 ('bob', 151),
 ('movies', 150),
 ('past', 150),
 ('report', 150),
 ('break', 150),
 ('gets', 150),
 ('quality', 150),
 ('playing', 149),
 ('front', 149),
 ('point', 148),
 ('sale', 148),
 ('bed', 148),
 ('fast', 147),
 ('america', 147),
 ('kinds', 147),
 ('passport', 147),
 ('online', 146),
 ('taken', 146),
 ('health', 146),
 ('suggest', 144),
 ('anyone', 144),
 ('close', 144),
 ('sports', 144),
 ('foreign', 144),
 ('ma', 144),
 ('goods', 143),
 ('become', 143),
 ('tickets', 143),
 ('takes', 143),
 ('test', 142),
 ('fact', 142),
 ('recently', 142),
 ('building', 142),
 ('bet', 142),
 ('less', 142),
 ('apply', 141),
 ('met', 141),
 ('christmas', 141),
 ('clean', 141),
 ('door', 141),
 ('york', 141),
 ('tour', 141),
 ('goes', 140),
 ('gone', 140),
 ('ah', 139),
 ('road', 139),
 ('instead', 139),
 ('lots', 139),
 ('type', 139),
 ('personal', 139),
 ('countries', 139),
 ('expect', 138),
 ('rib', 138),
 ('holiday', 137),
 ('lucky', 137),
 ('interest', 137),
 ('address', 137),
 ('style', 136),
 ('advice', 136),
 ('accept', 136),
 ('present', 136),
 ('light', 135),
 ('stand', 135),
 ('straight', 135),
 ('eyes', 135),
 ('choice', 135),
 ('monday', 134),
 ('shop', 134),
 ('games', 134),
 ('sound', 134),
 ('twenty', 134),
 ('station', 134),
 ('weight', 134),
 ('amount', 134),
 ('kitchen', 133),
 ('wants', 133),
 ('lovely', 133),
 ('total', 133),
 ('training', 133),
 ('stuff', 132),
 ('happen', 132),
 ('save', 132),
 ('goodbye', 132),
 ('hurry', 132),
 ('eight', 132),
 ('receipt', 132),
 ('kidding', 131),
 ('cup', 131),
 ('crazy', 130),
 ('ms', 130),
 ('forgot', 130),
 ('join', 130),
 ('c', 130),
 ('shoes', 130),
 ('brown', 130),
 ('system', 130),
 ('fit', 129),
 ('bag', 129),
 ('watching', 128),
 ('head', 128),
 ('planning', 128),
 ('leaving', 128),
 ('honey', 127),
 ('main', 127),
 ('convenient', 126),
 ('jack', 126),
 ('reason', 126),
 ('handle', 126),
 ('promise', 126),
 ('fresh', 126),
 ('famous', 126),
 ('area', 125),
 ('schedule', 125),
 ('language', 125),
 ('follow', 125),
 ('dear', 124),
 ('son', 124),
 ('whether', 124),
 ('careful', 124),
 ('students', 124),
 ('soup', 124),
 ('key', 124),
 ('shouldn', 123),
 ('student', 123),
 ('cook', 122),
 ('plans', 122),
 ('decision', 122),
 ('window', 121),
 ('god', 121),
 ('blue', 121),
 ('honest', 121),
 ('discount', 121),
 ('employees', 121),
 ('taste', 120),
 ('sense', 120),
 ('international', 120),
 ('studying', 120),
 ('town', 120),
 ('p', 120),
 ('finally', 119),
 ('double', 119),
 ('begin', 119),
 ('rain', 119),
 ('sort', 119),
 ('local', 119),
 ('london', 119),
 ('exciting', 118),
 ('running', 118),
 ('thousand', 118),
 ('exchange', 118),
 ('others', 117),
 ('boy', 117),
 ('quickly', 117),
 ('plenty', 117),
 ('sister', 117),
 ('meat', 116),
 ('breakfast', 116),
 ('library', 116),
 ('sell', 116),
 ('future', 116),
 ('project', 116),
 ('film', 115),
 ('wondering', 115),
 ('decide', 115),
 ('picture', 114),
 ('depends', 114),
 ('football', 114),
 ('longer', 113),
 ('driving', 112),
 ('places', 112),
 ('child', 112),
 ('smoking', 112),
 ('mrs', 112),
 ('fish', 112),
 ('mail', 112),
 ('rooms', 112),
 ('ice', 111),
 ('wedding', 111),
 ('loan', 111),
 ('taxi', 111),
 ('using', 110),
 ('hmm', 110),
 ('worth', 110),
 ('brother', 110),
 ('whatever', 109),
 ('sunday', 109),
 ('desk', 109),
 ('guys', 108),
 ('amazing', 108),
 ('classes', 108),
 ('program', 107),
 ('current', 107),
 ('french', 107),
 ('girlfriend', 107),
 ('asking', 107),
 ('seeing', 107),
 ('l', 107),
 ('piece', 106),
 ('example', 106),
 ('attention', 106),
 ('heavy', 106),
 ('excited', 106),
 ('clear', 106),
 ('heart', 106),
 ('gift', 106),
 ('eating', 106),
 ('hit', 105),
 ('baby', 105),
 ('saying', 105),
 ('contact', 105),
 ('girls', 105),
 ('according', 105),
 ('writing', 104),
 ('history', 104),
 ('learning', 104),
 ('swimming', 104),
 ('payment', 104),
 ('difference', 103),
 ('sent', 103),
 ('word', 103),
 ('beer', 103),
 ('knew', 103),
 ('pair', 103),
 ('companies', 103),
 ('performance', 102),
 ('notice', 102),
 ('learned', 102),
 ('government', 102),
 ('cake', 101),
 ('congratulations', 101),
 ('david', 101),
 ('mention', 101),
 ('airport', 101),
 ('final', 101),
 ('management', 101),
 ('application', 101),
 ('resume', 101),
 ('jim', 100),
 ('words', 100),
 ('prices', 100),
 ('worried', 100),
 ('enjoyed', 100),
 ('transfer', 100),
 ('healthy', 99),
 ('within', 99),
 ('touch', 99),
 ('space', 99),
 ('pm', 99),
 ('quiet', 99),
 ('mike', 99),
 ('answer', 99),
 ('discuss', 99),
 ('details', 99),
 ('costs', 98),
 ('medicine', 98),
 ('buying', 98),
 ('works', 98),
 ('public', 98),
 ('police', 98),
 ('simple', 98),
 ('spring', 98),
 ('plane', 98),
 ('gave', 97),
 ('luggage', 97),
 ('woman', 97),
 ('percent', 97),
 ('jobs', 97),
 ('id', 97),
 ('yours', 97),
 ('anymore', 96),
 ('cooking', 96),
 ('private', 96),
 ('club', 96),
 ('cannot', 96),
 ('somewhere', 96),
 ('visa', 96),
 ('vegetables', 95),
 ('tuesday', 95),
 ('ride', 95),
 ('nine', 95),
 ('women', 95),
 ('comfortable', 95),
 ('drinks', 94),
 ('everybody', 94),
 ('field', 94),
 ('telling', 94),
 ('received', 94),
 ('parking', 94),
 ('inside', 94),
 ('add', 94),
 ('higher', 93),
 ('strong', 93),
 ('nervous', 93),
 ('provide', 93),
 ('given', 93),
 ('staff', 93),
 ('lately', 92),
 ('cars', 92),
 ('corner', 92),
 ('latest', 92),
 ('um', 92),
 ('documents', 92),
 ('li', 92),
 ('behind', 92),
 ('blood', 92),
 ('twice', 92),
 ('package', 92),
 ('overtime', 92),
 ('customer', 92),
 ('subway', 92),
 ('bar', 91),
 ('fix', 91),
 ('wang', 91),
 ('environment', 91),
 ('box', 91),
 ('mark', 91),
 ('hospital', 91),
 ('message', 91),
 ('afford', 90),
 ('concert', 90),
 ('copy', 90),
 ('pounds', 90),
 ('skills', 90),
 ('particular', 90),
 ('daughter', 90),
 ('menu', 90),
 ('items', 90),
 ('necessary', 90),
 ('match', 89),
 ('likes', 89),
 ('ball', 89),
 ('teach', 89),
 ('skin', 89),
 ('sometime', 89),
 ('exam', 89),
 ('product', 89),
 ('customers', 89),
 ('spent', 89),
 ('meal', 89),
 ('trade', 89),
 ('prepare', 88),
 ('courses', 88),
 ('flowers', 88),
 ('step', 88),
 ('regular', 88),
 ('states', 88),
 ('men', 88),
 ('cheaper', 88),
 ('susan', 88),
 ('delivery', 88),
 ('services', 88),
 ('cream', 88),
 ('poor', 87),
 ('round', 87),
 ('view', 87),
 ('newspaper', 87),
 ('cover', 87),
 ('fair', 87),
 ('beach', 87)]

In [6]:
# pip install google-cloud-translate
from google.oauth2 import service_account
from google.cloud import translate_v2 as translate

# Load credentials from the JSON file
credentials = service_account.Credentials.from_service_account_file("../kt-languages-148ff3e33c54.json")

# Initialize client
translate_client = translate.Client(credentials=credentials)

# Example usage
result = translate_client.translate("Hello world", target_language="ru")
print(result["translatedText"])

Привет, мир

In [7]:
import argostranslate.package
import argostranslate.translate

# Update model index (list of all available models)
argostranslate.package.update_package_index()
available_packages = argostranslate.package.get_available_packages()

# Find the English → Russian package
package_to_install = next(
    pkg for pkg in available_packages
    if pkg.from_code == "en" and pkg.to_code == "ru"
)

# Install the package
argostranslate.package.install_from_path(package_to_install.download())

# Now load installed languages
installed_languages = argostranslate.translate.get_installed_languages()
from_lang = next(lang for lang in installed_languages if lang.code == "en")
to_lang = next(lang for lang in installed_languages if lang.code == "ru")

translation = from_lang.get_translation(to_lang)

# Test translation
print(translation.translate("Hello world, how are you?"))

/Users/kaitaoyang/Documents/dev/language_learning/.env/lib/python3.12/site-packages/stanza/models/tokenize/trainer.py:85: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)

Привет, мир, как дела?

In [8]:
# Apply row by row
# df["dialog_ru"] = df["dialog"].apply(translation.translate)
# df.to_csv("translated_partial.csv", index=False, encoding="utf-8-sig")

In [9]:
df = pd.read_csv("translated_partial_ru.csv")
text_raw_ru = " ".join(df["dialog_ru"].to_list()).lower()
len(text_raw_ru)

5294035

In [10]:
text_clean_ru_list = re.findall(r"[а-яё\-]+", text_raw_ru.replace("=", ""))
len(set(text_clean_ru_list))

41297

In [11]:
word_counter_ru = Counter(text_clean_ru_list)
word_counter_ru.most_common(1000)

[('я', 35162),
 ('в', 19696),
 ('это', 18690),
 ('что', 16827),
 ('не', 16507),
 ('вы', 14954),
 ('и', 13501),
 ('на', 10290),
 ('мне', 7615),
 ('ты', 7536),
 ('у', 6990),
 ('с', 6957),
 ('как', 6634),
 ('да', 6498),
 ('мы', 6220),
 ('но', 5871),
 ('бы', 5437),
 ('хорошо', 5080),
 ('есть', 4794),
 ('так', 4746),
 ('для', 4562),
 ('меня', 4537),
 ('о', 4484),
 ('он', 4172),
 ('могу', 3951),
 ('нет', 3845),
 ('чтобы', 3689),
 ('очень', 3689),
 ('все', 3537),
 ('вам', 3536),
 ('ли', 3479),
 ('спасибо', 3389),
 ('вас', 3236),
 ('думаю', 3063),
 ('его', 3061),
 ('если', 3048),
 ('они', 2980),
 ('за', 2790),
 ('пожалуйста', 2478),
 ('когда', 2470),
 ('быть', 2416),
 ('будет', 2413),
 ('просто', 2288),
 ('по', 2274),
 ('тебя', 2237),
 ('можете', 2180),
 ('конечно', 2170),
 ('ну', 2118),
 ('она', 2054),
 ('тебе', 2026),
 ('или', 2019),
 ('много', 1946),
 ('из', 1932),
 ('должны', 1825),
 ('еще', 1819),
 ('сегодня', 1818),
 ('был', 1814),
 ('сделать', 1808),
 ('к', 1793),
 ('было', 1786),
 ('время', 1782),
 ('здесь', 1767),
 ('нужно', 1741),
 ('почему', 1729),
 ('знаю', 1722),
 ('может', 1705),
 ('этом', 1698),
 ('действительно', 1636),
 ('чем', 1630),
 ('вот', 1628),
 ('а', 1600),
 ('нас', 1539),
 ('только', 1534),
 ('должен', 1503),
 ('-', 1485),
 ('хотел', 1484),
 ('хочу', 1460),
 ('где', 1425),
 ('от', 1409),
 ('нравится', 1378),
 ('сколько', 1373),
 ('их', 1356),
 ('мой', 1321),
 ('день', 1304),
 ('сейчас', 1295),
 ('больше', 1288),
 ('сэр', 1276),
 ('до', 1270),
 ('могли', 1210),
 ('этот', 1196),
 ('слишком', 1195),
 ('немного', 1194),
 ('привет', 1167),
 ('помочь', 1159),
 ('там', 1157),
 ('насчет', 1135),
 ('об', 1134),
 ('этого', 1130),
 ('тоже', 1071),
 ('нам', 1066),
 ('несколько', 1042),
 ('то', 1037),
 ('хотите', 982),
 ('можем', 936),
 ('правда', 920),
 ('также', 914),
 ('со', 913),
 ('тогда', 908),
 ('лучше', 907),
 ('ваш', 905),
 ('долларов', 903),
 ('один', 890),
 ('того', 877),
 ('себя', 877),
 ('раз', 854),
 ('знаете', 853),
 ('моя', 848),
 ('какой', 841),
 ('были', 831),
 ('всегда', 831),
 ('которые', 812),
 ('что-то', 812),
 ('ее', 806),
 ('уже', 790),
 ('теперь', 777),
 ('поэтому', 777),
 ('вижу', 776),
 ('пойти', 774),
 ('была', 770),
 ('буду', 765),
 ('получить', 763),
 ('же', 762),
 ('более', 759),
 ('извините', 755),
 ('эти', 754),
 ('делать', 751),
 ('всего', 751),
 ('уверен', 743),
 ('работу', 742),
 ('том', 739),
 ('хочешь', 739),
 ('звучит', 733),
 ('мистер', 726),
 ('пока', 725),
 ('возможно', 717),
 ('сказать', 714),
 ('после', 705),
 ('большое', 702),
 ('довольно', 701),
 ('времени', 696),
 ('никогда', 693),
 ('них', 686),
 ('что-нибудь', 678),
 ('потому', 676),
 ('через', 668),
 ('этой', 652),
 ('давайте', 652),
 ('порядке', 650),
 ('люди', 645),
 ('завтра', 642),
 ('эту', 638),
 ('вашей', 630),
 ('который', 630),
 ('надеюсь', 627),
 ('компании', 627),
 ('свой', 617),
 ('некоторые', 612),
 ('можешь', 601),
 ('люблю', 599),
 ('деле', 592),
 ('самом', 591),
 ('хотели', 590),
 ('моей', 587),
 ('стоит', 583),
 ('виду', 582),
 ('во', 580),
 ('купить', 578),
 ('вечером', 578),
 ('найти', 578),
 ('свою', 573),
 ('жаль', 567),
 ('около', 567),
 ('можно', 563),
 ('два', 562),
 ('сказал', 561),
 ('ничего', 553),
 ('этим', 546),
 ('боюсь', 541),
 ('работы', 540),
 ('кто', 535),
 ('прямо', 530),
 ('работать', 523),
 ('ваша', 523),
 ('обычно', 518),
 ('него', 517),
 ('ваше', 514),
 ('каждый', 510),
 ('отлично', 506),
 ('лет', 505),
 ('снова', 500),
 ('хорошая', 499),
 ('деньги', 499),
 ('думаете', 497),
 ('правильно', 495),
 ('должно', 495),
 ('мои', 493),
 ('сделал', 490),
 ('мной', 486),
 ('людей', 486),
 ('номер', 486),
 ('думал', 485),
 ('увидеть', 484),
 ('проблема', 482),
 ('ему', 479),
 ('посмотреть', 472),
 ('место', 468),
 ('утро', 468),
 ('такой', 463),
 ('идея', 453),
 ('слышал', 446),
 ('проблем', 446),
 ('минут', 446),
 ('рад', 445),
 ('затем', 442),
 ('знаешь', 442),
 ('какие', 439),
 ('здорово', 438),
 ('тобой', 438),
 ('ваши', 436),
 ('даже', 432),
 ('три', 430),
 ('какая', 428),
 ('вами', 428),
 ('своей', 428),
 ('дня', 425),
 ('интересно', 423),
 ('взять', 419),
 ('могут', 414),
 ('хороший', 414),
 ('использовать', 414),
 ('свои', 414),
 ('работа', 414),
 ('иметь', 412),
 ('вещи', 411),
 ('добро', 407),
 ('эта', 406),
 ('пожаловать', 406),
 ('кажется', 404),
 ('знать', 402),
 ('большой', 400),
 ('совсем', 400),
 ('новый', 398),
 ('денег', 392),
 ('доброе', 392),
 ('имеет', 391),
 ('дома', 389),
 ('часто', 389),
 ('является', 389),
 ('часов', 389),
 ('дать', 388),
 ('будут', 386),
 ('твой', 385),
 ('раньше', 383),
 ('случае', 382),
 ('выглядит', 379),
 ('видел', 372),
 ('случилось', 370),
 ('наш', 370),
 ('мог', 367),
 ('утром', 367),
 ('дней', 364),
 ('счет', 363),
 ('думаешь', 362),
 ('туда', 360),
 ('придется', 360),
 ('ей', 358),
 ('неделе', 356),
 ('разве', 354),
 ('увидимся', 353),
 ('почти', 345),
 ('нашей', 343),
 ('эй', 343),
 ('будете', 342),
 ('сначала', 342),
 ('течение', 341),
 ('собираюсь', 341),
 ('всех', 340),
 ('мисс', 340),
 ('наши', 337),
 ('мое', 336),
 ('иногда', 336),
 ('здравствуйте', 336),
 ('находится', 335),
 ('таким', 334),
 ('чувствую', 332),
 ('поговорить', 331),
 ('достаточно', 331),
 ('дела', 326),
 ('года', 325),
 ('кроме', 325),
 ('дом', 324),
 ('попробовать', 323),
 ('следующий', 322),
 ('приятно', 320),
 ('позвольте', 319),
 ('смогу', 318),
 ('проверить', 317),
 ('долго', 316),
 ('такое', 315),
 ('друг', 315),
 ('позже', 314),
 ('простите', 314),
 ('вчера', 312),
 ('сюда', 311),
 ('работе', 310),
 ('прошлой', 310),
 ('зовут', 310),
 ('нормально', 310),
 ('давай', 306),
 ('помощь', 305),
 ('им', 304),
 ('получил', 303),
 ('человек', 303),
 ('фильм', 303),
 ('дай', 302),
 ('которую', 300),
 ('плохо', 300),
 ('идти', 298),
 ('трудно', 297),
 ('никаких', 296),
 ('вместе', 293),
 ('куда', 292),
 ('возьму', 291),
 ('одна', 290),
 ('юаней', 290),
 ('имя', 289),
 ('домой', 289),
 ('верно', 289),
 ('говорить', 289),
 ('вау', 287),
 ('себе', 287),
 ('ни', 287),
 ('году', 287),
 ('скоро', 285),
 ('другой', 285),
 ('другие', 285),
 ('пять', 284),
 ('моего', 284),
 ('нужна', 280),
 ('ним', 279),
 ('прежде', 278),
 ('мэри', 275),
 ('нужен', 275),
 ('ужин', 274),
 ('дорогая', 274),
 ('понимаю', 274),
 ('компания', 274),
 ('назад', 271),
 ('пойдем', 270),
 ('выходные', 269),
 ('днем', 269),
 ('месяц', 268),
 ('когда-нибудь', 268),
 ('под', 266),
 ('похоже', 266),
 ('кофе', 265),
 ('год', 265),
 ('две', 264),
 ('вашу', 262),
 ('без', 262),
 ('наша', 259),
 ('быстро', 258),
 ('будем', 256),
 ('неделю', 255),
 ('свое', 255),
 ('рождения', 254),
 ('одну', 254),
 ('многие', 252),
 ('дело', 252),
 ('автобус', 252),
 ('самое', 251),
 ('вашего', 250),
 ('говорит', 250),
 ('работает', 249),
 ('которая', 249),
 ('билет', 248),
 ('играть', 247),
 ('нравятся', 246),
 ('твоя', 246),
 ('нее', 245),
 ('именно', 245),
 ('такие', 243),
 ('часть', 243),
 ('добрый', 243),
 ('пор', 242),
 ('мама', 240),
 ('этому', 237),
 ('принять', 237),
 ('любом', 237),
 ('ней', 236),
 ('вероятно', 234),
 ('комнату', 234),
 ('стороны', 234),
 ('имею', 233),
 ('мило', 233),
 ('легко', 231),
 ('первый', 231),
 ('видеть', 230),
 ('посмотрим', 230),
 ('кстати', 229),
 ('вашем', 225),
 ('рассказать', 225),
 ('жизни', 224),
 ('знал', 224),
 ('заказ', 222),
 ('какую', 221),
 ('тот', 221),
 ('заплатить', 219),
 ('позвонить', 218),
 ('прийти', 217),
 ('недели', 217),
 ('своего', 216),
 ('рядом', 215),
 ('намного', 214),
 ('купил', 213),
 ('начать', 213),
 ('познакомиться', 212),
 ('собой', 212),
 ('узнать', 212),
 ('проблемы', 212),
 ('комната', 212),
 ('должна', 211),
 ('последнее', 211),
 ('других', 211),
 ('имеешь', 210),
 ('своим', 209),
 ('особенно', 209),
 ('большинство', 208),
 ('неплохо', 208),
 ('платить', 207),
 ('делаешь', 206),
 ('следующей', 204),
 ('этих', 203),
 ('тем', 203),
 ('машину', 202),
 ('чего', 202),
 ('правы', 202),
 ('часа', 202),
 ('дайте', 202),
 ('говоря', 201),
 ('всем', 201),
 ('делает', 201),
 ('десять', 201),
 ('весь', 201),
 ('час', 201),
 ('показать', 200),
 ('мадам', 200),
 ('имеете', 199),
 ('офис', 199),
 ('ужасно', 197),
 ('ночью', 197),
 ('нем', 196),
 ('английский', 196),
 ('наших', 195),
 ('джон', 195),
 ('еду', 195),
 ('большая', 195),
 ('сделаю', 195),
 ('готовы', 195),
 ('выглядишь', 194),
 ('места', 194),
 ('нужны', 194),
 ('пойду', 194),
 ('еда', 193),
 ('четыре', 193),
 ('смотреть', 192),
 ('кто-то', 192),
 ('дни', 191),
 ('вечера', 191),
 ('сказали', 190),
 ('предложение', 190),
 ('волнуйся', 189),
 ('цена', 189),
 ('школе', 189),
 ('городе', 189),
 ('составляет', 189),
 ('выпить', 188),
 ('спросить', 188),
 ('над', 187),
 ('двух', 186),
 ('образом', 186),
 ('моим', 186),
 ('пару', 186),
 ('говорят', 185),
 ('смит', 185),
 ('нашего', 185),
 ('перед', 184),
 ('своих', 184),
 ('какое', 183),
 ('моих', 183),
 ('города', 182),
 ('права', 181),
 ('работаю', 181),
 ('дорого', 181),
 ('добраться', 181),
 ('жизнь', 180),
 ('хорошие', 180),
 ('вернуться', 180),
 ('мою', 180),
 ('согласен', 179),
 ('хорошее', 179),
 ('стране', 179),
 ('итак', 178),
 ('качестве', 177),
 ('готов', 177),
 ('форму', 177),
 ('делаю', 176),
 ('такая', 176),
 ('отправить', 176),
 ('собираешься', 175),
 ('ве', 175),
 ('ладно', 174),
 ('информацию', 173),
 ('идет', 172),
 ('вечер', 172),
 ('вещей', 171),
 ('оно', 171),
 ('комнате', 170),
 ('машина', 170),
 ('сделали', 170),
 ('хотя', 169),
 ('посмотрите', 169),
 ('между', 169),
 ('нашу', 169),
 ('детей', 168),
 ('интервью', 168),
 ('ищу', 167),
 ('минутку', 167),
 ('слышать', 167),
 ('опыт', 167),
 ('школу', 166),
 ('пятницу', 166),
 ('делают', 166),
 ('нами', 165),
 ('давно', 165),
 ('против', 165),
 ('ресторан', 165),
 ('полностью', 164),
 ('самый', 164),
 ('книги', 164),
 ('серьезно', 163),
 ('скажи', 162),
 ('тех', 162),
 ('сесть', 162),
 ('весело', 161),
 ('хочет', 161),
 ('ваших', 161),
 ('вопрос', 161),
 ('момент', 161),
 ('происходит', 160),
 ('большую', 160),
 ('заказать', 160),
 ('понравится', 159),
 ('взглянуть', 159),
 ('жить', 158),
 ('погода', 158),
 ('прошлом', 158),
 ('означает', 157),
 ('ночь', 157),
 ('утра', 156),
 ('месяца', 155),
 ('класс', 155),
 ('уверены', 155),
 ('компьютер', 155),
 ('способ', 155),
 ('отпуск', 154),
 ('месте', 154),
 ('свидания', 154),
 ('поздно', 153),
 ('какова', 153),
 ('рейс', 153),
 ('например', 152),
 ('комнаты', 152),
 ('тридцать', 151),
 ('далеко', 151),
 ('некоторое', 151),
 ('своем', 151),
 ('сша', 150),
 ('моем', 149),
 ('магазин', 149),
 ('видите', 149),
 ('решение', 149),
 ('письмо', 149),
 ('подходит', 149),
 ('поверить', 148),
 ('субботу', 148),
 ('из-за', 148),
 ('встреча', 148),
 ('выбор', 148),
 ('встретиться', 147),
 ('друзей', 147),
 ('будешь', 147),
 ('подождите', 147),
 ('получили', 147),
 ('поехать', 147),
 ('новую', 147),
 ('понравилось', 146),
 ('точно', 146),
 ('помогу', 146),
 ('видели', 146),
 ('парень', 145),
 ('сделаем', 145),
 ('возможность', 145),
 ('нашем', 145),
 ('которое', 145),
 ('вашим', 145),
 ('город', 145),
 ('сможем', 144),
 ('учиться', 144),
 ('конце', 144),
 ('двадцать', 144),
 ('занят', 144),
 ('сказала', 144),
 ('позвоню', 143),
 ('новые', 142),
 ('честно', 142),
 ('одного', 142),
 ('часы', 142),
 ('остаться', 142),
 ('ненавижу', 141),
 ('новости', 141),
 ('являются', 140),
 ('хорош', 140),
 ('другом', 140),
 ('улице', 140),
 ('месяцев', 140),
 ('человека', 139),
 ('выйти', 139),
 ('позволь', 139),
 ('сам', 138),
 ('уйти', 138),
 ('предпочитаю', 138),
 ('папа', 137),
 ('забыл', 137),
 ('карту', 137),
 ('выбрать', 137),
 ('идеально', 136),
 ('понял', 136),
 ('дети', 136),
 ('цвет', 136),
 ('размер', 136),
 ('отель', 136),
 ('школы', 135),
 ('подожди', 135),
 ('курс', 135),
 ('принести', 135),
 ('паспорт', 135),
 ('пройти', 134),
 ('хорошего', 134),
 ('боже', 134),
 ('займет', 134),
 ('одежду', 134),
 ('телефон', 134),
 ('ждать', 133),
 ('игры', 133),
 ('вокруг', 133),
 ('предложить', 133),
 ('всю', 132),
 ('имеют', 132),
 ('вина', 132),
 ('говоришь', 131),
 ('ко', 131),
 ('жена', 131),
 ('повезло', 131),
 ('вернусь', 131),
 ('собираетесь', 130),
 ('прекрасно', 130),
 ('телефона', 130),
 ('забрать', 130),
 ('отличная', 129),
 ('работал', 129),
 ('определенно', 129),
 ('нетерпением', 129),
 ('насколько', 129),
 ('никто', 129),
 ('шесть', 129),
 ('удовольствие', 129),
 ('менее', 129),
 ('прав', 128),
 ('любит', 128),
 ('понятия', 128),
 ('смотри', 128),
 ('твоей', 128),
 ('потом', 128),
 ('родители', 128),
 ('ценю', 128),
 ('изменить', 128),
 ('ними', 127),
 ('девушка', 127),
 ('друзьями', 127),
 ('автомобиль', 127),
 ('мере', 127),
 ('рано', 127),
 ('такси', 127),
 ('скорее', 127),
 ('делаете', 126),
 ('месяце', 126),
 ('китае', 126),
 ('встречу', 126),
 ('цены', 126),
 ('при', 126),
 ('поезд', 126),
 ('спать', 125),
 ('последний', 125),
 ('офисе', 125),
 ('стол', 125),
 ('волосы', 125),
 ('заполните', 125),
 ('позволить', 124),
 ('последние', 124),
 ('нескольких', 124),
 ('важно', 124),
 ('абсолютно', 124),
 ('провести', 123),
 ('получите', 123),
 ('зависит', 123),
 ('вообще', 123),
 ('полагаю', 123),
 ('какие-либо', 123),
 ('счета', 123),
 ('замечательно', 122),
 ('поскольку', 122),
 ('области', 122),
 ('резюме', 122),
 ('гораздо', 121),
 ('своими', 121),
 ('недель', 121),
 ('хорошую', 121),
 ('доктор', 121),
 ('попросить', 120),
 ('основном', 120),
 ('вернуть', 120),
 ('помню', 120),
 ('дождь', 120),
 ('банк', 120),
 ('нашим', 120),
 ('сможете', 120),
 ('иду', 119),
 ('план', 119),
 ('встречи', 119),
 ('друга', 119),
 ('вопросы', 119),
 ('книгу', 118),
 ('классе', 118),
 ('говорил', 118),
 ('хотят', 118),
 ('одной', 118),
 ('во-первых', 118),
 ('адрес', 118),
 ('вид', 117),
 ('слышали', 117),
 ('платье', 117),
 ('понадобится', 116),
 ('глаза', 116),
 ('подарок', 116),
 ('закончил', 116),
 ('семья', 115),
 ('удобно', 115),
 ('получу', 115),
 ('семь', 115),
 ('примерно', 115),
 ('раза', 114),
 ('людьми', 114),
 ('круто', 114),
 ('сложно', 114),
 ('решил', 114),
 ('цену', 114),
 ('плата', 114),
 ('интернете', 113),
 ('откуда', 113),
 ('босс', 113),
 ('лучший', 113),
 ('путь', 113),
 ('трех', 112),
 ('потерял', 112),
 ('компанию', 112),
 ('крайней', 111),
 ('прости', 111),
 ('части', 111),
 ('звоню', 111),
 ('минуту', 110),
 ('ходить', 110),
 ('язык', 110),
 ('список', 110),
 ('телевизор', 110),
 ('вместо', 110),
 ('миссис', 110),
 ('данный', 110),
 ('отец', 109),
 ('доллара', 109),
 ('новых', 109),
 ('оставаться', 109),
 ('подождать', 109),
 ('второй', 108),
 ('одно', 108),
 ('которой', 108),
 ('отсюда', 108),
 ('пошли', 107),
 ('начал', 107),
 ('считаю', 107),
 ('пить', 107),
 ('некоторых', 107),
 ('меньше', 107),
 ('сих', 107),
 ('наше', 107),
 ('нового', 106),
 ('доме', 106),
 ('оба', 106),
 ('знает', 106),
 ('бизнес', 106),
 ('восемь', 106),
 ('документы', 106),
 ('чувствовать', 105),
 ('следующем', 105),
 ('любое', 105),
 ('жду', 105),
 ('однажды', 105),
 ('любите', 105),
 ('возражаете', 105),
 ('быстрее', 105),
 ('учитель', 104),
 ('шанс', 104),
 ('вечеринка', 104),
 ('менеджер', 104),
 ('интернет', 104),
 ('любимый', 104),
 ('боб', 104),
 ('равно', 104),
 ('забронировать', 104),
 ('автобусе', 104),
 ('понедельник', 103),
 ('пришел', 103),
 ('ночи', 103),
 ('пришли', 103),
 ('чай', 103),
 ('поможет', 102),
 ('мире', 102),
 ('университет', 102),
 ('держать', 102),
 ('значит', 102),
 ('воды', 102),
 ('большие', 102),
 ('игра', 101),
 ('джек', 101),
 ('столик', 101),
 ('удачи', 101),
 ('новая', 101),
 ('китай', 101),
 ('будь', 101),
 ('еды', 100),
 ('багаж', 100),
 ('читать', 100),
 ('рабочий', 100),
 ('шутишь', 100),
 ('носить', 100),
 ('холодно', 100),
 ('посмотри', 100),
 ('продукты', 100),
 ('чек', 100),
 ('кино', 99),
 ('покупки', 99),
 ('отличный', 99),
 ('боль', 99),
 ('дам', 99),
 ('заполнить', 99),
 ('стоимость', 99),
 ('стоить', 99),
 ('квартиру', 99),
 ('говорите', 98),
 ('вещь', 98),
 ('машины', 98),
 ('совершенно', 98),
 ('страны', 98),
 ('удовольствием', 98),
 ('говорю', 98),
 ('метро', 98),
 ('заявку', 98),
 ('муж', 98),
 ('истории', 97),
 ('взял', 97),
 ('тому', 97),
 ('ох', 97),
 ('обед', 97),
 ('решить', 97),
 ('подумать', 97),
 ('поздравляю', 96),
 ('колледже', 96),
 ('музыка', 96),
 ('планы', 96),
 ('мира', 96),
 ('прекрасный', 96),
 ('открыть', 96),
 ('суп', 96),
 ('иди', 96),
 ('подать', 96),
 ('готовить', 95),
 ('шоу', 95),
 ('ах', 95),
 ('стать', 95),
 ('сразу', 95),
 ('закончить', 95),
 ('мало', 95),
 ('вовремя', 95),
 ('идешь', 95),
 ('этаже', 95),
 ('личности', 94),
 ('кого', 94),
 ('планируете', 94),
 ('виды', 94),
 ('клиентов', 94),
 ('делал', 94),
 ('оставить', 94),
 ('другое', 94),
 ('китайский', 94),
 ('меню', 94),
 ('красиво', 94),
 ('написать', 94),
 ('совет', 93),
 ('нашел', 93),
 ('посетить', 93),
 ('пути', 93),
 ('какие-нибудь', 93),
 ('вернулся', 92),
 ('устал', 92),
 ('думать', 92),
 ('пяти', 92),
 ('любят', 92),
 ('карта', 92),
 ('стиль', 91),
 ('вечеринку', 91),
 ('фильмы', 91),
 ('решили', 91),
 ('друзья', 91),
 ('понять', 91),
 ('костюм', 91),
 ('твои', 91),
 ('таких', 91),
 ('мэм', 91),
 ('будто', 90),
 ('вкус', 90),
 ('хотим', 90),
 ('разных', 90),
 ('университете', 90),
 ('забудьте', 90),
 ('цвета', 90),
 ('лучшее', 89),
 ('пришло', 89),
 ('рада', 89),
 ('поездка', 89),
 ('сильно', 89),
 ('семье', 89),
 ('должность', 89),
 ('квартира', 89),
 ('услуги', 89),
 ('лицо', 88),
 ('пекине', 88),
 ('новой', 88),
 ('скажу', 88),
 ('каковы', 88),
 ('зарплата', 87),
 ('ребенок', 86),
 ('такую', 86),
 ('такого', 86),
 ('фунтов', 86),
 ('внимание', 86),
 ('обучение', 86),
 ('хмм', 86),
 ('летом', 86),
 ('стивен', 86),
 ('заинтересованы', 86),
 ('другую', 86),
 ('карты', 86),
 ('пришлось', 86),
 ('сообщение', 86),
 ('семьи', 85),
 ('ван', 85),
 ('становится', 85),
 ('прошло', 85),
 ('хуже', 85),
 ('повышение', 85),
 ('начнем', 85),
 ('большим', 85),
 ('кое-что', 85),
 ('контракт', 85),
 ('смотрю', 84),
 ('видишь', 84),
 ('недостаточно', 84),
 ('потрясающе', 84),
 ('другими', 84),
 ('сделано', 84)]

In [12]:
df_words_ru = pd.DataFrame(word_counter_ru.most_common(), columns=["word", "count"])
df_words_ru.sort_values(by="count", ascending=False, inplace=True)
df_words_ru

                word  count
0                  я  35162
1                  в  19696
2                это  18690
3                что  16827
4                 не  16507
...              ...    ...
30580       кубертен      1
30581    возрождении      1
30582     профессору      1
30583  отсутствовали      1
41296     выставлены      1

[41297 rows x 2 columns]

In [13]:
import pymorphy3

morph = pymorphy3.MorphAnalyzer()

df_words_ru["root"] = df_words_ru["word"].apply(lambda x: morph.parse(x)[0].normal_form)
print(df_words_ru.root.nunique())
print(df_words_ru.word.nunique())
df_words_ru_root = (
    df_words_ru.groupby("root").agg({"word": list}).reset_index(drop=False)
)
df_words_ru_root["nwords"] = df_words_ru_root.word.apply(len)
df_words_ru_root = df_words_ru_root.sort_values("nwords", ascending=False).reset_index(
    drop=True
)
df_words_ru_root.to_csv("df_words_ru_root.csv", encoding="utf-8-sig", index=False)
display(df_words_ru_root)

15879
41297

               root                                               word  nwords
0           хороший  [лучше, хорошая, хороший, хорошие, хорошее, хо...      34
1      использовать  [использовать, используете, использую, использ...      27
2           сделать  [сделать, сделал, сделаю, сделали, сделаем, сд...      26
3           высокий  [высокий, высокая, высокие, высокого, высокой,...      25
4            плохой  [хуже, плохой, плохая, плохого, плохое, плохие...      23
...             ...                                                ...     ...
15874         наана                                             [наан]       1
15875      набивать                                         [набивают]       1
15876       набивка                                         [набивкой]       1
15877        набить                                           [набить]       1
15878            ён                                               [ён]       1

[15879 rows x 3 columns]

In [14]:
from itertools import chain


class TrieNode:
    def __init__(self):
        self.children = {}
        self.count = 0
        self.word_indices = []  # store indices of words passing through


class Trie:
    def __init__(self):
        self.root = TrieNode()

    def insert(self, word, index):
        node = self.root
        for ch in word:
            if ch not in node.children:
                node.children[ch] = TrieNode()
            node = node.children[ch]
            node.count += 1
            node.word_indices.append(index)


def find_longest_prefix_groups(words, min_group_size=2, min_prefix_len=3):
    """
    Iteratively find LONGEST prefixes having >= min_group_size words.
    Optimized: word indices are stored in trie nodes, so we avoid rescanning.
    """
    remaining = list(range(len(words)))  # track indices instead of words
    groups = {}

    while True:
        # Build trie for current remaining indices
        trie = Trie()
        for idx in remaining:
            trie.insert(words[idx], idx)

        new_groups = {}

        def dfs(node, prefix):
            found_child_group = False
            for ch, child in node.children.items():
                if child.count >= min_group_size:
                    dfs(child, prefix + ch)
                    found_child_group = True
            if (
                node.count >= min_group_size
                and not found_child_group
                and len(prefix) >= min_prefix_len
            ):
                new_groups[prefix] = [words[i] for i in node.word_indices]

        dfs(trie.root, "")

        if not new_groups:
            break

        groups.update(new_groups)
        grouped = set(chain.from_iterable(new_groups.values()))
        remaining = [i for i in remaining if words[i] not in grouped]

    singletons = [words[i] for i in remaining]
    return groups, singletons


# Example usage
words = df_words_ru_root.root

prefix_groups, prefix_singletons = find_longest_prefix_groups(
    words, min_group_size=2, min_prefix_len=3
)

print(len(prefix_groups))
print(len(prefix_singletons))
for sub, words in prefix_groups.items():
    print(sub, words)

print(prefix_singletons)

6033
1344
хорошеньк ['хорошенький', 'хорошенько']
хорн ['хорнтаун', 'хорн']
ход ['ходить', 'ход', 'ходьба', 'ходатайство']
хотеть ['хотеть', 'хотеться']
холодно ['холодное', 'холодно', 'холодность']
холостя ['холостяцкий', 'холостяк']
холм ['холм', 'холмистый', 'холмс']
холл ['холл', 'холль']
хозяй ['хозяйство', 'хозяйка']
хост ['хостел', 'хостинг']
хоккей ['хоккей', 'хоккейный']
хоп ['хопскочий', 'хопкинс']
хон ['хон', 'хонбо', 'хонг', 'хонда', 'хоннинга']
хоу ['хоум-ран', 'хоу']
художественн ['художественный', 'художественно']
хун ['хун', 'хунаня', 'хунг', 'хуном']
хуанг ['хуанга', 'хуангуосить']
хуанх ['хуанхуан', 'хуанхэ']
хранить ['хранить', 'храниться']
храбр ['храбрый', 'храбрость', 'храбрец']
храм ['храмовый', 'храм']
хруст ['хрустеть', 'хруст', 'хрустковы', 'хрустальный']
христиан ['христианин', 'христианский']
хрома ['хрома', 'хромать']
хрони ['хроника', 'хронический']
хре ['хребет', 'хрень']
хваст ['хвастаться', 'хвастовство']
хват ['хватать', 'хватка', 'хватить']
хвост ['хвост', 'хвостатый']
характери ['характеристика', 'характеризовать']
харрис ['харрисон', 'харрис']
хаке ['хакер', 'хакетта']
хала ['халат', 'халапенос']
хад ['хадж', 'хад', 'хадсон']
хант ['хантереть', 'хантлить']
хань ['ханьский', 'ханьцами', 'ханьчжоуский']
хайн ['хайнань', 'хайнекен']
хайд ['хайджек', 'хайдарабад']
хаотичн ['хаотично', 'хаотичный']
хамм ['хамма', 'хаммера']
хаб ['хабеас', 'хаббнуть']
ха-ха ['ха-ха', 'ха-ха-ха']
химик ['химик', 'химикат', 'химик-исследователь']
хитро ['хитро', 'хитрость', 'хитроу']
хищ ['хищение', 'хищник']
хирурги ['хирургия', 'хирургический']
хип ['хип-хоп', 'хип']
хилл ['хилла', 'хилл']
хэл ['хэллоуин', 'хэла', 'хэлмитон']
хэнсон ['хэнсон', 'хэнсоном']
хэнкс ['хэнкс', 'хэнкса']
хэм ['хэмилтон', 'хэмлина']
хьюстон ['хьюстон', 'хьюстонский']
хла ['хлам', 'хладнокровно']
хлеб ['хлеб', 'хлебный', 'хлебец']
хлопот ['хлопотный', 'хлопоты', 'хлопот']
хей ['хейвуд', 'хейлнести', 'хейс']
хел ['хелен', 'хеллен']
хмм ['хммм', 'хмм']
использовать ['использовать', 'использоваться']
исполнить ['исполниться', 'исполнить']
исполнять ['исполнять', 'исполняться']
испортить ['испортить', 'испортиться']
исправи ['исправить', 'исправимый']
исправл ['исправление', 'исправлять']
испан ['испанский', 'испания']
испытат ['испытать', 'испытательный']
испу ['испугаться', 'испускать']
искусственн ['искусственный', 'искусственно']
искупит ['искупительный', 'искупить']
исключительн ['исключительный', 'исключительно']
исключа ['исключая', 'исключать']
искренн ['искренний', 'искренность', 'искренне']
исследователь ['исследовательский', 'исследователь']
исчез ['исчезать', 'исчезнуть']
истори ['история', 'исторический', 'историк']
истощ ['истощённый', 'истощить']
истин ['истинный', 'истина']
истеч ['истечь', 'истечение']
истери ['истерик', 'истерически']
истр ['истребитель', 'истратить']
исход ['исходить', 'исходящий']
исцелить ['исцелиться', 'исцелить']
иса ['исаак', 'иса']
идеальн ['идеальный', 'идеально']
идентификаци ['идентификация', 'идентификационный']
идентичн ['идентичный', 'идентичность']
идиом ['идиом', 'идиоматический']
игра ['играть', 'игра']
игро ['игрок', 'игровой']
игруш ['игрушка', 'игрушечный']
игл ['игла', 'иглоукалывание', 'иглесиас']
игнорировать ['игнорировать', 'игнорироваться']
иметь ['иметь', 'иметься']
именно ['именно', 'именной']
импортировать ['импортировать', 'импортироваться']
импортн ['импортный', 'импортно-экспортный']
император ['император', 'императорский']
иммиграци ['иммиграционный', 'иммиграция']
иммун ['иммунизация', 'иммунный']
ими ['имидж', 'имитировать']
имбир ['имбирь', 'имбирный']
изменить ['изменить', 'измениться']
измельчит ['измельчить', 'измельчитель']
измеритель ['измеритель', 'измерительный']
измерять ['измерять', 'измеряться']
известно ['известно', 'известность']
извергать ['извергать', 'извергаться']
извинить ['извиниться', 'извинить']
извле ['извлечь', 'извлекаться']
изучать ['изучать', 'изучаться']
избавить ['избавиться', 'избавить']
избавл ['избавляться', 'избавление']
избе ['избегать', 'избежать']
избиратель ['избирательный', 'избиратель']
избыто ['избыточный', 'избыток']
избра ['избрать', 'избранный']
изысканн ['изысканный', 'изысканно']
издавать ['издавать', 'издаваться']
издательс ['издательский', 'издательство']
изде ['изделие', 'издеваться']
изготов ['изготовить', 'изготовление']
изгна ['изгнание', 'изгнать']
изображ ['изображение', 'изображать']
изобразит ['изобразительный', 'изобразить']
изобрет ['изобретение', 'изобретательный']
изогнут ['изогнуть', 'изогнутый']
изол ['изолятор', 'изолировать']
излиш ['излишество', 'излишний']
износ ['износить', 'износ']
изна ['изначально', 'изнашиваться']
изабел ['изабелла', 'изабель']
из- ['из-под', 'из-за']
изящн ['изящно', 'изящный']
интересн ['интересный', 'интересно']
интересовать ['интересовать', 'интересоваться']
интервьюировать ['интервьюировать', 'интервьюироваться']
интернет-с ['интернет-сервис', 'интернет-сайт', 'интернет-соединение', 'интернет-список']
интернет-банк ['интернет-банк', 'интернет-банкинга', 'интернет-банковский']
интернет-п ['интернет-план', 'интернет-подразделение']
интерпрет ['интерпретировать', 'интерпретация']
интенсивно ['интенсивно', 'интенсивность']
интеллектуал ['интеллектуальный', 'интеллектуал']
интегр ['интегрировать', 'интеграция']
интроверт ['интроверт', 'интровертный']
иностран ['иностранный', 'иностранец', 'иностранка']
индивидуально ['индивидуально', 'индивидуальность']
инде ['индейка', 'индеец', 'индекс']
инду ['индустрия', 'индукционный', 'индуистский']
индонези ['индонезия', 'индонезиец']
инвестици ['инвестиционный', 'инвестиция']
инвестирова ['инвестировать', 'инвестирование']
инвестор ['инвестор', 'инвестор-любитель']
инвалидн ['инвалидность', 'инвалидный']
инструк ['инструктор', 'инструкция']
инсти ['институт', 'инстинкт']
инспекци ['инспекция', 'инспекционный']
информаци ['информационный', 'информация']
информати ['информативный', 'информатика']
инфекци ['инфекция', 'инфекционный']
инг ['ингредиент', 'ингибитор', 'ингалятор']
инженер-ме ['инженер-механик', 'инженер-менеджер']
инициа ['инициатива', 'инициал']
инноваци ['инновационный', 'инновация']
итальян ['итальянский', 'итальянец']
итог ['итог', 'итоговый']
ит-ко ['ит-компания', 'ит-консультант']
ит-с ['ит-сервисный', 'ит-специалист']
иер ['иероглиф', 'иерархия']
ипоте ['ипотека', 'ипотечный']
ирланд ['ирландский', 'ирландия', 'ирландец']
ирони ['ирония', 'иронично']
иран ['иран', 'иранец']
ике ['икебана', 'икеа']
сдел ['сделать', 'сделка']
сдержа ['сдержать', 'сдержанно']
сдавать ['сдавать', 'сдаваться']
сдать ['сдать', 'сдаться']
сломать ['сломать', 'сломаться']
сложно ['сложность', 'сложно']
сложить ['сложиться', 'сложить']
словар ['словарь', 'словарный']
слон ['слоновый', 'слон']
следователь ['следователь', 'следовательно']
следств ['следствие', 'следственный']
слепо ['слепой', 'слепо']
слеза ['слеза', 'слезать']
слушат ['слушать', 'слушатель']
случайно ['случайность', 'случайно']
служит ['служить', 'служитель']
служе ['служебный', 'служение']
слыш ['слышать', 'слышный']
слабо ['слабость', 'слаборазвитый', 'слабо']
сладкое ['сладкое', 'сладкоежка']
слав ['славиться', 'слава', 'славный']
слайд- ['слайд-трек', 'слайд-шоу']
слан ['сланцевый', 'сланец']
сливо ['сливочный', 'сливовый']
сливать ['сливаться', 'сливать']
сильн ['сильный', 'сильно']
сиден ['сидение', 'сидень']
сидней ['сидней', 'сиднейский']
сидя ['сидячий', 'сидя']
сингапур ['сингапур', 'сингапурский', 'сингапурец']
синь ['синьцзян', 'синьхая', 'синь']
синт ['синтетический', 'синтия']
сино ['синоптик', 'синоним']
система ['система', 'систематический']
сия ['сиять', 'сияющий']
сит ['ситуация', 'ситком', 'сити']
символ ['символ', 'символизировать']
симпати ['симпатия', 'симпатичный']
сигнализ ['сигнализация', 'сигнализировать']
сигарет ['сигарета', 'сигаретный']
сир ['сироп', 'сирс', 'сирлоина', 'сирена']
сиан ['сианя', 'сиангка', 'сиана']
сказать ['сказать', 'сказаться']
скали ['скалистый', 'скалиона']
скачива ['скачивать', 'скачивание']
скандал ['скандал', 'скандальный']
сканирова ['сканировать', 'сканирование']
скат ['скатерть', 'скатывать']
скучн ['скучный', 'скучно']
скул ['скульптура', 'скула']
скид ['скидка', 'скидочный']
скрыть ['скрыться', 'скрыть']
скромно ['скромность', 'скромно']
скрести ['скрестить', 'скрести']
скреп ['скрепка', 'скрепить']
скрип ['скрипка', 'скрипичный', 'скрипач']
скручивать ['скручиваться', 'скручивать']
скра ['скрапинг', 'скрам', 'скраб']
скорост ['скорость', 'скоростной']
скорб ['скорбь', 'скорбный', 'скорбеть']
скольз ['скользкий', 'скользить']
сковород ['сковородка', 'сковорода']
складывать ['складывать', 'складываться']
склонн ['склонный', 'склонность']
скейтборд ['скейтборд', 'скейтбординг']
сквоз ['сквозняк', 'сквозь']
свободн ['свободный', 'свободно']
свой ['свой', 'свойство']
сводить ['сводить', 'сводиться']
своевременн ['своевременный', 'своевременно']
свеже ['свежеть', 'свежесть', 'свежеприготовленный']
светло- ['светло-голубой', 'светло-коричневый', 'светло-зелёный']
свето ['светофор', 'световой']
светить ['светиться', 'светить']
светил ['светильник', 'светило']
сверху ['сверхурочный', 'сверху']
связать ['связать', 'связаться']
связывать ['связывать', 'связываться']
священн ['священный', 'священник', 'священнослужитель']
свад ['свадебный', 'свадьба']
свал ['свалка', 'свалить']
свар ['сварка', 'сварщик']
свидетельство ['свидетельство', 'свидетельствовать']
свино ['свиной', 'свиноматка']
свинин ['свинина', 'свинин']
свист ['свистеть', 'свисток']
счастлив ['счастливый', 'счастливчик', 'счастливо', 'счастливица']
считать ['считать', 'считаться']
счёт ['счёт', 'счётчик', 'счёт-фактура', 'счётный']
строго ['строгость', 'строго']
строй ['стройный', 'строй']
строитель ['строительство', 'строительный', 'строитель']
страда ['страдать', 'страдание']
страхова ['страхование', 'страховать']
страна ['страна', 'страна-импортёр']
странн ['странный', 'странно']
стратеги ['стратегия', 'стратегический']
страшн ['страшный', 'страшно']
страст ['страстный', 'страсть']
стрельб ['стрельба', 'стрельбище']
стрелк ['стрелка', 'стрелковый']
стресс ['стресс', 'стрессовый']
стремит ['стремиться', 'стремительно']
струн ['струна', 'струнный']
структур ['структура', 'структурировать']
стричь ['стричься', 'стричь']
стриптиз ['стриптизёрша', 'стриптиз']
старши ['старший', 'старшинство']
старшеклассни ['старшеклассник', 'старшеклассница']
старомодн ['старомодный', 'старомодно']
стари ['старик', 'старинный', 'старичок']
старе ['стареть', 'старейшина']
стартов ['стартовый', 'стартовать']
стартер ['стартер', 'стартерный']
стару ['старушка', 'старуха']
стать ['стать', 'статья']
стату ['статуя', 'статус', 'статуэтка']
статисти ['статистика', 'статистический']
стандартн ['стандартный', 'стандартно']
станов ['становиться', 'становление']
сталк ['сталкиваться', 'сталкер']
став ['ставка', 'ставить']
стабильн ['стабильный', 'стабильность']
стади ['стадия', 'стадион']
стакан ['стакан', 'стаканчик']
стажиров ['стажировка', 'стажироваться']
стои ['стоить', 'стоимость']
столкн ['столкнуться', 'столкновение']
столет ['столетие', 'столетний']
столов ['столовая', 'столовый']
столб ['столб', 'столбовщик', 'столбик']
столи ['столик', 'столица', 'столичный']
столь ['столько', 'столь']
сторон ['сторона', 'сторонник']
стоматологи ['стоматологический', 'стоматология']
стойк ['стойка', 'стойкость', 'стойкий']
стоян ['стоянка', 'стояночный']
стоп- ['стоп-сигнал', 'стоп-уведомление']
стон ['стон', 'стонать']
стильн ['стильный', 'стильно']
стили ['стилия', 'стилист', 'стилизовать']
стира ['стирать', 'стиральный']
стивен ['стивен', 'стивенс']
стимулирова ['стимулировать', 'стимулирование']
стимуляци ['стимуляция', 'стимуляционный']
стих ['стихийный', 'стих', 'стихотворение']
стинг ['стингер', 'стинг']
стенографи ['стенография', 'стенографический', 'стенографирование']
стейк ['стейк', 'стейков', 'стейк-ужин']
стейт ['стейт-стрит', 'стейт']
стерео ['стереосистема', 'стереотип', 'стерео']
стерл ['стерлинг', 'стерлета']
стекл ['стеклянный', 'стекло']
степ ['степень', 'степлера']
стефан ['стефани', 'стефан']
студент- ['студент-мужчина', 'студент-инженер']
студи ['студия', 'студийный']
стучать ['стучать', 'стучаться']
ступ ['ступить', 'ступенчатый', 'ступать']
стюард ['стюардесса', 'стюард']
стык ['стыковочный', 'стык']
стыд ['стыд', 'стыдиться', 'стыдно']
стёр ['стёртый', 'стёрн']
стэнли ['стэнли-парк', 'стэнли']
смотреть ['смотреть', 'смотреться']
смоч ['смочь', 'смочиться']
смен ['сменить', 'смена', 'сменный']
смешать ['смешать', 'смешаться']
смешно ['смешной', 'смешно']
смешивать ['смешивать', 'смешиваться']
смета ['сметать', 'сметана']
смело ['смелость', 'смело']
смехотворно ['смехотворность', 'смехотворно']
смертельн ['смертельный', 'смертельно']
смес ['смесь', 'смести', 'смеситель']
смит ['смит', 'смитсом', 'смитфилд']
смирен ['смиренный', 'смирение']
смывать ['смывать', 'смываться']
смущать ['смущать', 'смущаться']
смаз ['смазка', 'смазывать', 'смазать']
смягчить ['смягчиться', 'смягчить']
современн ['современный', 'современно']
совершать ['совершать', 'совершаться']
совершенно ['совершеннолетие', 'совершенно']
совет ['совет', 'советовать', 'советник']
совмести ['совместимый', 'совместительство']
совпад ['совпадать', 'совпадение']
сова ['совать', 'сова']
совокуп ['совокупный', 'совокуплять']
соответств ['соответствовать', 'соответствующий', 'соответствие', 'соответственно']
соотно ['соотношение', 'соотноситься']
сообщать ['сообщать', 'сообщаться']
сообще ['сообщение', 'сообщество']
создат ['создать', 'создатель']
созре ['созреть', 'созревать', 'созрелый']
созыв ['созыв', 'созывать']
собирать ['собираться', 'собирать']
собственни ['собственник', 'собственнический']
собрать ['собрать', 'собраться']
собака ['собака', 'собака-гончая']
собач ['собачий', 'собачка']
собо ['собор', 'соболезнование']
соблюд ['соблюдать', 'соблюдение']
соблазн ['соблазнить', 'соблазн']
сойти ['сойти', 'сойтись']
составлять ['составлять', 'составляться']
состоять ['состоять', 'состояться']
соседс ['соседство', 'соседский']
сосредоточить ['сосредоточить', 'сосредоточиться']
сосн ['сосна', 'сосновый']
сосущ ['сосущий', 'сосуществовать']
социальн ['социальный', 'социально-экономический']
солнечн ['солнечный', 'солнечно']
солнце ['солнцезащитный', 'солнце', 'солнцестойкий']
соль ['соль', 'сольный']
солом ['соломон', 'соломинка', 'соломенный']
солидн ['солидный', 'солидно']
сотруднич ['сотрудничать', 'сотрудничество']
сохранить ['сохранить', 'сохраниться']
сократить ['сократить', 'сократиться']
сокращать ['сокращать', 'сокращаться']
согласи ['согласиться', 'согласие']
согласован ['согласование', 'согласованность']
согласн ['согласный', 'согласно']
соглаш ['соглашение', 'соглашаться']
согреть ['согреть', 'согреться']
согнут ['согнуть', 'согнутый']
сожале ['сожалеть', 'сожаление']
сонлив ['сонливый', 'сонливость']
сонг ['сонгхуа', 'сонг']
сочетать ['сочетаться', 'сочетать']
сочувств ['сочувствие', 'сочувствовать']
сочин ['сочинять', 'сочинить']
сомне ['сомневаться', 'сомнение']
соединит ['соединить', 'соединительный']
соединять ['соединять', 'соединяться']
сорвать ['сорвать', 'сорваться']
соревнова ['соревнование', 'соревноваться']
сорок ['сорок', 'сороковой', 'сорокаэтажный', 'сорок-восемьдесят']
сорт ['сорт', 'сортировать']
сопровожд ['сопровождать', 'сопровождение']
сопроводит ['сопроводительный', 'сопроводить']
сопротивл ['сопротивление', 'сопротивляться']
сопостави ['сопоставимый', 'сопоставить']
союзн ['союзный', 'союзник']
содержать ['содержаться', 'содержать']
содейств ['содействовать', 'содействие']
софи ['софия', 'софи']
самообслужива ['самообслуживание', 'самообслуживаться']
самоу ['самоубийство', 'самоучкой']
самоз ['самоз', 'самозванец', 'самозащита']
самостоятельн ['самостоятельный', 'самостоятельно']
самор ['самородковый', 'саморекомендация', 'саморазвитие']
саймон ['саймон', 'саймонс']
садовод ['садоводство', 'садоводческий']
салат ['салат', 'салатный', 'салат-бар']
саль ['сальса', 'сальто']
салли ['саллик', 'салли']
сара ['сара', 'сарай']
саркастич ['саркастический', 'саркастичный']
сантехник ['сантехника', 'сантехник']
санта- ['санта-моника', 'санта-клаус', 'санта-барбара']
санг ['сангрия', 'санга']
санитар ['санитарный', 'санитария']
сандал ['сандалия', 'сандалс', 'сандал']
сандр ['сандри', 'сандра']
сан- ['сан-диего', 'сан-франциско', 'сан-паулу']
сань ['санья', 'саньюань']
саунд ['саундтрек', 'саундсом']
саут ['саут', 'саутгемптон']
сатин ['сатина', 'сатиновый']
сап ['сапог', 'сапфир', 'саппоро']
сак ['сакстон', 'сак']
спокойн ['спокойный', 'спокойно']
спорт ['спортивный', 'спорт', 'спортзал', 'спортсмен']
способн ['способный', 'способность']
спонсор ['спонсорство', 'спонсор']
спонсирова ['спонсироваться', 'спонсирование']
спасти ['спасти', 'спастись']
спасатель ['спасательный', 'спасатель']
спаситель ['спаситель', 'спасительница']
спальн ['спальня', 'спальный', 'спальник', 'спальная']
спам- ['спам-фильтр', 'спам-письмо', 'спам-нежелательный']
спа- ['спа-салон', 'спа-процедура']
спрос ['спросить', 'спрос']
справедливо ['справедливость', 'справедливо']
спрятать ['спрятаться', 'спрятать']
спре ['спреть', 'спреда']
специально ['специальность', 'специально']
специализировать ['специализироваться', 'специализировать']
специфика ['спецификация', 'специфика']
спеш ['спешить', 'спешка']
спел ['спелый', 'спельта']
спект ['спектакль', 'спектр']
спекул ['спекулянт', 'спекулировать']
спустить ['спуститься', 'спустить']
спускать ['спускаться', 'спускать']
спутник ['спутниковый', 'спутник']
спис ['список', 'списать']
спин ['спина', 'спинка', 'спин', 'спинстер']
спидо ['спидометр', 'спидос']
спич ['спичка', 'спичечный']
спиртно ['спиртной', 'спиртное']
сплетни ['сплетничать', 'сплетник']
серьёзно ['серьёзно', 'серьёзность']
сертифика ['сертификат', 'сертификация']
сертифицирова ['сертифицированный', 'сертифицировать']
сердечн ['сердечный', 'сердечно-лёгочный']
сердит ['сердиться', 'сердитый']
сери ['сериал', 'серия', 'серить', 'серийный']
серебрист ['серебристый', 'серебристо-серый']
сервис ['сервис', 'сервисный']
семе ['семейный', 'семестр', 'семеро']
семь- ['семь-тридцать', 'семь-пятнадцать']
семидесят ['семидесятый', 'семидесятипроцентный']
семнадцат ['семнадцать', 'семнадцатый']
сегодня ['сегодняшний', 'сегодня']
сестра ['сестра', 'сестра-близнец']
сельск ['сельский', 'сельскохозяйственный']
селл ['селлерс', 'селлара']
сели ['селия', 'селина']
секретар ['секретарь', 'секретарша', 'секретарский']
сексуальн ['сексуальный', 'сексуально']
сексист ['сексистский', 'сексист']
секундо ['секундомер', 'секундочка']
сект ['сектор', 'сектантка']
седло ['седло', 'седлов']
северо-запад ['северо-западный', 'северо-запад']
северо-восто ['северо-восток', 'северо-восточный']
сенс ['сенсорный', 'сенсация']
сент-дж ['сент-джонс', 'сент-джеймс']
сей ['сейф', 'сейчас', 'сейсмический', 'сеймур', 'сейл-ит', 'сейв', 'сей']
себ ['себя', 'себестоимость']
сет ['сеть', 'сетевой', 'сеттер', 'сетка']
сеп ['сепия', 'сепаратист']
срочно ['срочность', 'срочно']
средне- ['средне-хорошо', 'средне-редкий']
срез ['срезать', 'срез']
сравнивать ['сравнивать', 'сравниваться']
сравнить ['сравнить', 'сравниться']
сравнительн ['сравнительный', 'сравнительно']
сраж ['сражаться', 'сражение']
сраз ['сразу', 'сразиться']
снизить ['снизить', 'снизиться']
снимать ['снимать', 'сниматься']
снижать ['снижаться', 'снижать']
снять ['снять', 'сняться']
снего ['снегопад', 'снеговик', 'снегоступ']
снар ['снаряжение', 'снаружи']
снова ['снова-б', 'снова']
сухо ['сухой', 'сухофрукт', 'сухо']
сумм ['сумма', 'суммировать']
сумер ['сумеречный', 'сумерки']
суперма ['супермаркет', 'супермагистраль']
супербад ['супербада', 'супербад']
супер- ['супер-мальчик', 'супер-галстук']
супру ['супружеский', 'супруг']
существо ['существовать', 'существо']
судебн ['судебный', 'судебно-медицинский']
судь ['судья', 'судьба']
судоход ['судоходство', 'судоходный']
судостро ['судостроительный', 'судостроение']
судн ['судно', 'судный']
сувенир ['сувенир', 'сувенирный']
суббот ['суббота', 'субботний']
суши ['сушилка', 'сушить']
сужден ['суждение', 'суждено']
сур ['суровый', 'сурфа']
сузить ['сузить', 'сузиться']
сует ['суетливый', 'суетиться', 'суета']
суевер ['суеверный', 'суеверие']

In [15]:
from itertools import chain


class TrieNode:
    def __init__(self):
        self.children = {}
        self.count = 0
        self.word_indices = []  # store indices of words passing through


class Trie:
    def __init__(self):
        self.root = TrieNode()

    def insert(self, word, index):
        node = self.root
        for ch in word:
            if ch not in node.children:
                node.children[ch] = TrieNode()
            node = node.children[ch]
            node.count += 1
            node.word_indices.append(index)


def find_longest_suffix_groups(words, min_group_size=2, min_suffix_len=3):
    """
    Iteratively find LONGEST suffixes having >= min_group_size words.
    Optimized: store word indices at nodes in trie of reversed words.
    """
    remaining = list(range(len(words)))  # indices
    groups = {}

    while True:
        trie = Trie()
        for idx in remaining:
            trie.insert(words[idx][::-1], idx)  # insert reversed word

        new_groups = {}

        def dfs(node, suffix_rev):
            found_child_group = False
            for ch, child in node.children.items():
                if child.count >= min_group_size:
                    dfs(child, suffix_rev + ch)
                    found_child_group = True
            if (
                node.count >= min_group_size
                and not found_child_group
                and len(suffix_rev) >= min_suffix_len
            ):
                suffix = suffix_rev[::-1]  # flip back to original direction
                new_groups[suffix] = [words[i] for i in node.word_indices]

        dfs(trie.root, "")

        if not new_groups:
            break

        groups.update(new_groups)
        grouped = set(chain.from_iterable(new_groups.values()))
        remaining = [i for i in remaining if words[i] not in grouped]

    singletons = [words[i] for i in remaining]
    return groups, singletons

# Example usage
words = df_words_ru_root.root

suffix_groups, suffix_singletons = find_longest_suffix_groups(
    words, min_group_size=2, min_suffix_len=3
)


# Print results
print(len(suffix_groups))
print(len(suffix_singletons))

print("Shared suffix groups:")
for suffix, group_words in suffix_groups.items():
    print(f"'{suffix}' -> {group_words}")

print("\nSingletons (no shared suffix):")
print(suffix_singletons)

5488
1365
Shared suffix groups:
'рший' -> ['старший', 'умерший']
'младший' -> ['младший', 'буш-младший']
'шедший' -> ['сумасшедший', 'прошедший']
'бывший' -> ['бывший', 'новоприбывший']
'евший' -> ['устаревший', 'потерпевший']
'окий' -> ['высокий', 'глубокий', 'широкий', 'одинокий', 'жестокий']
'изкий' -> ['близкий', 'низкий']
'енький' -> ['маленький', 'новенький', 'хорошенький']
'мягкий' -> ['мягкий', 'умеренно-мягкий']
'роткий' -> ['короткий', 'кроткий']
'аткий' -> ['краткий', 'шаткий']
'икий' -> ['великий', 'дикий']
'австралийский' -> ['австралийский', 'китайско-австралийский']
'лимпийский' -> ['олимпийский', 'паралимпийский']
'бийский' -> ['колумбийский', 'лесбийский']
'китайский' -> ['китайский', 'древнекитайский', 'англо-китайский']
'майский' -> ['майский', 'ямайский']
'корейский' -> ['корейский', 'южнокорейский']
'технический' -> ['технический', 'сантехнический']
'анический' -> ['механический', 'органический', 'вулканический', 'ботанический']
'енический' -> ['гигиенический', 'сценический']
'онический' -> ['симфонический', 'хронический', 'платонический']
'ористический' -> ['юмористический', 'террористический']
'листический' -> ['социалистический', 'филателистический']
'фантастический' -> ['фантастический', 'научно-фантастический']
'оматический' -> ['автоматический', 'идиоматический']
'тематический' -> ['математический', 'тематический', 'систематический']
'ократический' -> ['демократический', 'аристократический']
'политический' -> ['политический', 'космополитический']
'актический' -> ['фактический', 'практический', 'профилактический']
'тетический' -> ['эстетический', 'синтетический']
'отический' -> ['экзотический', 'патриотический']
'ептический' -> ['эпилептический', 'антисептический']
'экономический' -> ['экономический', 'социально-экономический']
'смический' -> ['космический', 'сейсмический']
'метрический' -> ['газометрический', 'метрический']
'исторический' -> ['исторический', 'доисторический']
'юридический' -> ['юридический', 'параюридический']
'нологический' -> ['технологический', 'хронологический']
'кологический' -> ['экологический', 'онкологический']
'иологический' -> ['биологический', 'физиологический']
'еологический' -> ['теологический', 'геологический']
'рологический' -> ['астрологический', 'метеорологический']
'лический' -> ['металлический', 'католический', 'гидравлический']
'нографический' -> ['стенографический', 'порнографический']
'греческий' -> ['греческий', 'древнегреческий']
'коммерческий' -> ['коммерческий', 'некоммерческий']
'енческий' -> ['студенческий', 'управленческий', 'приключенческий']
'оводческий' -> ['садоводческий', 'животноводческий']
'ружеский' -> ['дружеский', 'супружеский']
'етский' -> ['детский', 'университетский', 'египетский', 'массачусетский', 'ламбетский']
'азиатский' -> ['азиатский', 'всеазиатский', 'восточноазиатский']
'ентский' -> ['президентский', 'клиентский', 'агентский', 'абонентский']
'антский' -> ['гигантский', 'комендантский']
'истский' -> ['альпинистский', 'сексистский', 'журналистский', 'индуистский']
'медицинский' -> ['медицинский', 'судебно-медицинский']
'нкинский' -> ['нанкинский', 'янкинский']
'тинский' -> ['латинский', 'аргентинский']
'ринский' -> ['сестринский', 'мандаринский']
'ританский' -> ['британский', 'пуританский']
'оамериканский' -> ['афроамериканский', 'латиноамериканский']
'панский' -> ['испанский', 'шампанский']
'вегетарианский' -> ['вегетарианский', 'невегетарианский']
'океанский' -> ['океанский', 'тихоокеанский', 'трансокеанский']
'манский' -> ['гурманский', 'мусульманский']
'янский' -> ['итальянский', 'гаитянский']
'венский' -> ['рождественский', 'венский']
'стонский' -> ['бостонский', 'йеллоустонский', 'хьюстонский']
'шпионский' -> ['шпионский', 'антишпионский']
'стерский' -> ['вестминстерский', 'манчестерский']
'лидерский' -> ['лидерский', 'черлидерский']
'тёрский' -> ['актёрский', 'волонтёрский']
'арский' -> ['секретарский', 'швейцарский', 'варварский', 'пекарский', 'ниагарский']
'аторский' -> ['императорский', 'организаторский']
'урский' -> ['сингапурский', 'сатурский']
'-банковский' -> ['интернет-банковский', 'онлайн-банковский']
'ровский' -> ['рокфеллеровский', 'кассировский']
'левский' -> ['нобелевский', 'королевский']
'бительский' -> ['потребительский', 'любительский']
'одительский' -> ['водительский', 'родительский']
'исследовательский' -> ['исследовательский', 'научно-исследовательский']
'преподавательский' -> ['родительско-преподавательский', 'преподавательский']
'ольский' -> ['монгольский', 'польский', 'креольский']
'ханьский' -> ['уханьский', 'ханьский']
'оский' -> ['плоский', 'броский']
'одский' -> ['заводский', 'трехгородский']
'рдский' -> ['оксфордский', 'гарвардский']
'ландский' -> ['голландский', 'ирландский', 'шотландский']
'едский' -> ['соседский', 'шведский']
'удский' -> ['бермудский', 'голливудский']
'сский' -> ['русский', 'техасский']
'жский' -> ['кембриджский', 'парижский']
'йоркский' -> ['нью-йоркский', 'йоркский']
'гский' -> ['гонконгский', 'чикагский', 'эдинбургский']
'омский' -> ['томский', 'оклахомский']
'кингемский' -> ['букингемский', 'бакингемский']
'тонкий' -> ['тонкий', 'ультратонкий', 'микротонкий']
'редкий' -> ['редкий', 'средне-редкий']
'сладкий' -> ['сладкий', 'горько-сладкий']
'бкий' -> ['гибкий', 'робкий']
'рецкий' -> ['турецкий', 'дворецкий', 'грецкий']
'ацкий' -> ['дурацкий', 'рыбацкий']
'омкий' -> ['громкий', 'ломкий']
'липкий' -> ['липкий', 'хлипкий']
'аркий' -> ['жаркий', 'паркий']
'лкий' -> ['мелкий', 'жалкий']
'який' -> ['всякий', 'двоякий']
'ловкий' -> ['неловкий', 'ловкий']
'стойкий' -> ['термостойкий', 'солнцестойкий', 'стойкий']
'многий' -> ['многий', 'немногий']
'долгий' -> ['долгий', 'недолгий']
'вежий' -> ['свежий', 'медвежий']
'охожий' -> ['похожий', 'прохожий']
'редний' -> ['средний', 'передний']
'огодний' -> ['новогодний', 'прошлогодний']
'утренний' -> ['внутренний', 'утренний']
'искренний' -> ['искренний', 'неискренний']
'сенний' -> ['весенний', 'осенний']
'усторонний' -> ['двусторонний', 'потусторонний']
'носторонний' -> ['односторонний', 'разносторонний']
'нешний' -> ['внешний', 'нынешний']
'вчерашний' -> ['вчерашний', 'позавчерашний']
'лишний' -> ['лишний', 'излишний']
'черний' -> ['вечерний', 'дочерний']
'нолетний' -> ['несовершеннолетний', 'однолетний']
'хлетний' -> ['двухлетний', 'трёхлетний']
'ятилетний' -> ['пятилетний', 'десятилетний']
'ижний' -> ['нижний', 'ближний']
'замужний' -> ['замужний', 'незамужний']
'давний' -> ['недавний', 'давний']
'но-синий' -> ['тёмно-синий', 'чёрно-синий']
'мний' -> ['зимний', 'кремний']
'ений' -> ['гений', 'олений']
'настоящий' -> ['настоящий', 'ненастоящий']
'остоящий' -> ['дорогостоящий', 'противостоящий']
'подходящий' -> ['подходящий', 'неподходящий']
'курящий' -> ['некурящий', 'курящий']
'говорящий' -> ['говорящий', 'неанглоговорящий']
'следующий' -> ['следующий', 'последующий']
'ствующий' -> ['существующий', 'соответствующий']
'оляющий' -> ['умоляющий', 'болеутоляющий']
'нающий' -> ['начинающий', 'знающий']
'хватывающий' -> ['захватывающий', 'всеохватывающий']
'жающий' -> ['окружающий', 'раздражающий', 'освежающий']
'дущий' -> ['будущий', 'ведущий', 'предыдущий', 'грядущий']
'есущий' -> ['вездесущий', 'несущий']
'надлежащий' -> ['надлежащий', 'ненадлежащий']
'очий' -> ['рабочий', 'хопскочий']
'ячий' -> ['горячий', 'сидячий']
'ачий' -> ['собачий', 'девчачий', 'кошачий']
'ючий' -> ['вонючий', 'горючий']
'тий' -> ['третий', 'литий']
'нарий' -> ['сценарий', 'линарий']
'терий' -> ['критерий', 'кафетерий']
'вий' -> ['гравий', 'коровий']
'лий' -> ['капитолий', 'василий', 'гелий']
'плохой' -> ['плохой', 'неплохой', 'суперплохой']
'сухой' -> ['сухой', 'полусухой']
'дой' -> ['молодой', 'худой']
'простой' -> ['простой', 'непростой']
'устой' -> ['пустой', 'густой']
'нятой' -> ['занятой', 'снятой']
'витой' -> ['развитой', 'витой']
'прямой' -> ['прямой', 'непрямой']
'ьмой' -> ['восьмой', 'седьмой']
'омой' -> ['хромой', 'домой']
'немой' -> ['чэнемой', 'немой']
'ловой' -> ['деловой', 'силовой', 'яблочко-головой', 'угловой', 'тепловой']
'ховой' -> ['страховой', 'верховой', 'меховой']
'ировой' -> ['мировой', 'безжировой']
'годовой' -> ['годовой', 'полугодовой']
'ичасовой' -> ['восьмичасовой', 'шестичасовой']
'очасовой' -> ['почасовой', 'одночасовой', 'многочасовой']
'осовой' -> ['голосовой', 'носовой']
'роковой' -> ['сороковой', 'роковой']
'аковой' -> ['таковой', 'каковой']
'звуковой' -> ['звуковой', 'ультразвуковой']
'ветовой' -> ['цветовой', 'световой']
'еговой' -> ['беговой', 'береговой']
'волновой' -> ['волновой', 'микроволновой']
'чевой' -> ['ключевой', 'мочевой', 'плечевой']
'олевой' -> ['полевой', 'солевой', 'долевой', 'голевой', 'волевой']
'улевой' -> ['рулевой', 'нулевой']
'биржевой' -> ['биржевой', 'внебиржевой']
'тевой' -> ['гостевой', 'сетевой', 'локтевой']
'цевой' -> ['лицевой', 'кольцевой']
'стальной' -> ['остальной', 'стальной']
'менной' -> ['временной', 'именной']
'чной' -> ['ночной', 'ручной', 'речной', 'лисичной']
'скоростной' -> ['скоростной', 'высокоскоростной', 'десятискоростной', '-скоростной']
'ртной' -> ['портной', 'спиртной']
'головной' -> ['головной', 'надголовной']
'островной' -> ['островной', 'полуостровной']
'ивной' -> ['подливной', 'отбивной', 'пивной']
'увной' -> ['обувной', 'надувной']
'стяной' -> ['шерстяной', 'жестяной', 'костяной']
'дяной' -> ['ледяной', 'водяной', 'сельдяной']
'вяной' -> ['кровяной', 'травяной']
'ходной' -> ['выходной', 'входной', 'проходной']
'адной' -> ['прикладной', 'наградной']
'шной' -> ['смешной', 'сплошной', 'ушной']
'ойной' -> ['двойной', 'тройной']
'бной' -> ['зубной', 'грибной', 'гребной']
'писной' -> ['записной', 'подписной']
'пускной' -> ['выпускной', 'отпускной', 'пропускной', 'впускной']
'казной' -> ['заказной', 'показной']
'иной' -> ['свиной', 'иной']
'ерной' -> ['дверной', 'номерной']
'пной' -> ['цепной', 'выхлопной', 'покупной']
'какой' -> ['какой', 'никакой', 'кое-какой']
'морской' -> ['морской', 'военно-морской']
'дской' -> ['городской', 'складской']
'голубой' -> ['голубой', 'светло-голубой']
'большой' -> ['большой', 'небольшой']
'дорогой' -> ['дорогой', 'недорогой']
'угой' -> ['другой', 'тугой']
'упой' -> ['тупой', 'скупой']
'орой' -> ['второй', 'порой']
'крой' -> ['покрой', 'закрой']
'строй' -> ['строй', 'устрой', 'настрой']
'жилой' -> ['жилой', 'пожилой']
'жой' -> ['чужой', 'джой']
'леновый' -> ['кленовый', 'полиэтиленовый']
'атиновый' -> ['платиновый', 'сатиновый']
'зиновый' -> ['резиновый', 'бензиновый']
'тановый' -> ['каштановый', 'титановый']
'лоновый' -> ['слоновый', 'нейлоновый']
'здоровый' -> ['здоровый', 'нездоровый']
'ятидолларовый' -> ['пятидолларовый', 'десятидолларовый']
'метровый' -> ['-миллиметровый', '-метровый', 'километровый']
'хлитровый' -> ['трёхлитровый', 'двухлитровый']
'отовый' -> ['готовый', 'сотовый', 'терракотовый']
'почтовый' -> ['почтовый', 'авиапочтовый']
'стовый' -> ['текстовый', 'тестовый', 'холстовый']
'фиолетовый' -> ['фиолетовый', 'ультрафиолетовый']
'уктовый' -> ['фруктовый', 'продуктовый']
'портовый' -> ['портовый', 'аэропортовый']
'центовый' -> ['-центовый', 'четырехцентовый']
'итовый' -> ['нефритовый', 'самсонитовый']
'футовый' -> ['двенадцатифутовый', '-футовый']
'финансовый' -> ['финансовый', 'онлайн-финансовый']
'исовый' -> ['рисовый', 'арахисовый', 'тисовый']
'ассовый' -> ['массовый', 'кассовый']
'асовый' -> ['ананасовый', 'басовый', 'одиннадцатичасовый']
'ксовый' -> ['факсовый', 'коксовый']
'раковый' -> ['раковый', 'завтраковый']
'тниковый' -> ['спутниковый', 'тростниковый']
'риковый' -> ['материковый', 'шариковый']
'ликовый' -> ['роликовый', 'карликовый']
'лковый' -> ['шёлковый', 'стрелковый']
'дисковый' -> ['трехдисковый', 'дисковый']
'уковый' -> ['луковый', 'бамбуковый']
'вековый' -> ['средневековый', 'многовековый']
'стковый' -> ['известковый', 'подростковый']
'рковый' -> ['парковый', 'норковый']
'торговый' -> ['торговый', 'внешнеторговый', 'онлайн-торговый']
'тинговый' -> ['маркетинговый', 'рекрутинговый', 'консалтинговый']
'налоговый' -> ['налоговый', 'безналоговый', 'аналоговый']
'разовый' -> ['одноразовый', 'трехразовый']
'ндовый' -> ['фондовый', 'лавандовый']
'одовый' -> ['содовый', 'кодовый']
'дюймовый' -> ['-дюймовый', 'однодюймовый', 'двухдюймовый']
'бовый' -> ['бобовый', 'дубовый', 'крабовый']
'головый' -> ['трехголовый', 'безголовый']
'ерцовый' -> ['перцовый', 'четырехгигагерцовый']
'красивый' -> ['красивый', 'некрасивый']
'счастливый' -> ['счастливый', 'несчастливый']
'отливый' -> ['заботливый', 'кропотливый', 'неприхотливый']
'етливый' -> ['суетливый', 'приветливый']
'справедливый' -> ['справедливый', 'несправедливый']
'вежливый' -> ['вежливый', 'невежливый']
'терпеливый' -> ['терпеливый', 'нетерпеливый']
'нивый' -> ['ленивый', 'ревнивый']
'менчивый' -> ['изменчивый', 'переменчивый']
'манчивый' -> ['заманчивый', 'обманчивый']
'рчивый' -> ['придирчивый', 'доверчивый', 'разговорчивый']
'думчивый' -> ['задумчивый', 'вдумчивый']
'приимчивый' -> ['предприимчивый', 'невосприимчивый']
'олюбивый' -> ['трудолюбивый', 'честолюбивый']
'шивый' -> ['паршивый', 'фальшивый']
'ёвый' -> ['дешёвый', 'вишнёвый', 'лососёвый']
'правый' -> ['правый', 'неправый']
'то-коричневый' -> ['золотисто-коричневый', 'красновато-коричневый']
'левый' -> ['левый', 'эйфелевый', 'ролевый']
'жевый' -> ['оранжевый', 'бежевый']
'шевый' -> ['плюшевый', 'грушевый']
'ниевый' -> ['алюминиевый', 'кремниевый']
'нцевый' -> ['глянцевый', 'сланцевый']
'стрый' -> ['быстрый', 'острый']
'который' -> ['который', 'некоторый']
'брый' -> ['добрый', 'храбрый']
'дрый' -> ['щедрый', 'мудрый', 'бодрый']
'о-серый' -> ['тёмно-серый', 'серебристо-серый']
'о-красный' -> ['ярко-красный', 'желтовато-красный', 'кларетно-красный']
'безопасный' -> ['безопасный', 'небезопасный']
'огласный' -> ['согласный', 'единогласный']
'интересный' -> ['интересный', 'неинтересный']
'весный' -> ['древесный', 'легковесный']
'офисный' -> ['офисный', 'межофисный']
'сервисный' -> ['сервисный', 'ит-сервисный']
'кусный' -> ['вкусный', 'искусный', 'бесфокусный']
'русный' -> ['антивирусный', 'парусный']
'ясный' -> ['ясный', 'потрясный']
'оклассный' -> ['первоклассный', 'высококлассный']
'плексный' -> ['комплексный', 'дуплексный']
'носный' -> ['смертоносный', 'кровеносный']
'сильный' -> ['сильный', 'бессильный']
'правильный' -> ['правильный', 'неправильный']
'мобильный' -> ['автомобильный', 'мобильный']
'стабильный' -> ['стабильный', 'нестабильный']
'стильный' -> ['стильный', 'текстильный']
'нильный' -> ['ванильный', 'чернильный']
'чательный' -> ['замечательный', 'окончательный']
'влекательный' -> ['привлекательный', 'увлекательный', 'развлекательный']
'етательный' -> ['изобретательный', 'летательный']
'обязательный' -> ['обязательный', 'необязательный']
'щательный' -> ['тщательный', 'вещательный']
'овательный' -> ['образовательный', 'очаровательный', 'требовательный', 'основательный', 'последовательный']
'авательный' -> ['плавательный', 'познавательный']
'евательный' -> ['жевательный', 'нагревательный']
'внимательный' -> ['внимательный', 'невнимательный']
'гательный' -> ['сберегательный', 'трогательный']
'нежелательный' -> ['нежелательный', 'спам-нежелательный']
'дательный' -> ['рекомендательный', 'наблюдательный', 'законодательный']
'знательный' -> ['признательный', 'подсознательный']
'удивительный' -> ['удивительный', 'неудивительный']
'действительный' -> ['действительный', 'недействительный']
'овительный' -> ['оздоровительный', 'подготовительный']
'авительный' -> ['представительный', 'поздравительный']
'полнительный' -> ['дополнительный', 'исполнительный']
'удовлетворительный' -> ['удовлетворительный', 'неудовлетворительный']
'варительный' -> ['предварительный', 'пищеварительный']
'зрительный' -> ['зрительный', 'подозрительный']
'ерительный' -> ['измерительный', 'верительный']
'значительный' -> ['значительный', 'незначительный']
'ключительный' -> ['заключительный', 'исключительный']
'личительный' -> ['отличительный', 'увеличительный']
'учительный' -> ['поучительный', 'мучительный']
'длительный' -> ['длительный', 'медлительный']
'стительный' -> ['растительный', 'вместительный', 'непростительный']
'жительный' -> ['положительный', 'раздражительный', 'продолжительный', 'головокружительный']
'упительный' -> ['вступительный', 'искупительный']
'одительный' -> ['сопроводительный', 'снисходительный']
'остроительный' -> ['судостроительный', 'машиностроительный']
'общительный' -> ['общительный', 'необщительный']
'ешительный' -> ['решительный', 'утешительный']
'ушительный' -> ['разрушительный', 'оглушительный']
'мительный' -> ['утомительный', 'изумительный']
'осительный' -> ['относительный', 'вопросительный']
'разительный' -> ['изобразительный', 'выразительный', 'поразительный']
'ятельный' -> ['самостоятельный', 'влиятельный', 'обаятельный']
'хнедельный' -> ['двухнедельный', 'трехнедельный']
'модельный' -> ['модельный', 'мультимодельный']
'табельный' -> ['респектабельный', 'рентабельный', 'комфортабельный', 'нечитабельный']
'ебельный' -> ['мебельный', 'стебельный']
'фельный' -> ['картофельный', 'вафельный']
'мегапиксельный' -> ['-мегапиксельный', 'восьмимегапиксельный', 'мегапиксельный']
'реальный' -> ['реальный', 'лореальный']
'официальный' -> ['официальный', 'неофициальный']
'енциальный' -> ['потенциальный', 'конфиденциальный', 'преференциальный']
'ниальный' -> ['колониальный', 'гениальный']
'ориальный' -> ['лобориальный', 'мемориальный']
'профессиональный' -> ['профессиональный', 'непрофессиональный']
'национальный' -> ['национальный', 'общенациональный', 'многонациональный', 'транснациональный', 'интернациональный']
'функциональный' -> ['функциональный', 'многофункциональный']
'оминальный' -> ['номинальный', 'поминальный']
'формальный' -> ['формальный', 'неформальный']
'нормальный' -> ['нормальный', 'ненормальный']
'имальный' -> ['максимальный', 'минимальный']
'музыкальный' -> ['музыкальный', 'мини-музыкальный']
'икальный' -> ['уникальный', 'вертикальный', 'радикальный', 'клерикальный']
'бальный' -> ['глобальный', 'бальный']
'тральный' -> ['центральный', 'театральный', 'нейтральный']
'натуральный' -> ['натуральный', '-натуральный']
'неральный' -> ['генеральный', 'минеральный']
'копировальный' -> ['копировальный', 'фотокопировальный']
'начальный' -> ['первоначальный', 'начальный']
'ктуальный' -> ['пунктуальный', 'интеллектуальный', 'актуальный']
'визуальный' -> ['визуальный', 'аудиовизуальный']
'спальный' -> ['двуспальный', 'спальный', 'односпальный']
'ментальный' -> ['документальный', 'фундаментальный']
'континентальный' -> ['континентальный', 'межконтинентальный']
'стальный' -> ['хрустальный', 'пристальный']
'дальный' -> ['феодальный', 'скандальный', 'пирамидальный']
'школьный' -> ['школьный', 'дошкольный']
'тбольный' -> ['футбольный', 'баскетбольный']
'алкогольный' -> ['безалкогольный', 'алкогольный']
'угольный' -> ['угольный', 'краеугольный']
'довольный' -> ['довольный', 'недовольный']
'польный' -> ['напольный', 'топольный']
'трольный' -> ['контрольный', 'гастрольный']
'сольный' -> ['сольный', 'фасольный']
'ыльный' -> ['прибыльный', 'мыльный']
'ульный' -> ['титульный', 'патрульный']
'модный' -> ['модный', 'старомодный']
'народный' -> ['международный', 'народный']
'агородный' -> ['загородный', 'благородный']
'доходный' -> ['судоходный', 'подоходный']
'олодный' -> ['холодный', 'голодный']
'выгодный' -> ['выгодный', 'взаимовыгодный', 'невыгодный']
'пригодный' -> ['непригодный', 'пригодный']
'оводный' -> ['беспроводный', 'глубоководный', 'пресноводный']
'судный' -> ['ссудный', 'судный']
'вредный' -> ['вредный', 'безвредный']
'кладный' -> ['складный', 'накладный']
'западный' -> ['западный', 'северо-западный']
'радный' -> ['виноградный', 'парадный', 'эстрадный']
'здный' -> ['звёздный', 'праздный', 'поздный', 'подъездный']
'ендный' -> ['арендный', 'дивидендный']
'дальновидный' -> ['дальновидный', 'недальновидный']
'лидный' -> ['инвалидный', 'солидный']
'ардный' -> ['кардный', 'миллиардный']
'людный' -> ['многолюдный', 'людный']
'рядный' -> ['заурядный', 'зарядный']
'доступный' -> ['доступный', 'недоступный', 'труднодоступный']
'важный' -> ['важный', 'отважный']
'бумажный' -> ['бумажный', 'хлопчатобумажный']
'тражный' -> ['арбитражный', 'короткометражный']
'хэтажный' -> ['двухэтажный', 'трёхэтажный']

In [16]:
shared_sigletons = set(prefix_singletons).intersection(set(suffix_singletons))
unshared_sigletons = set(prefix_singletons).union(set(suffix_singletons)) - shared_sigletons
print(len(shared_sigletons))
print(len(unshared_sigletons))
print(shared_sigletons)
print(unshared_sigletons)

395
1919
{'вто', 'этв', 'о-к', 'юк', 'дюйм', 'фаджит', 'вблизи', 'иба', 'фея', 'шакил', 'лу', 'льюис', 'мэр', 'журавль', 'мазь', 'ви', 'сша', 'не', 'вейл', 'ляо', 'тег', 'мэл', 'лувр', 'ли', 'м', 'хех', 'ж', 'тахо', 'аа', 'бла', 'зря', 'зомби', 'алмаз', 'её', 'е-', 'пук', 'даг', 'лёжа', 'а', 'с', 'чак', 'пэн', 'до', 'в-третьих', 'бидпай', 'бао', 'чехол', 'экипаж', 'э-бф', 'лю', 'тигр', 'пиджак', 'астма', 'огайо', 'ён', 'эээ', 'ус', 'оф', 'ах', 'от', 'хум', 'кт', 'мощь', 'чат', 'акм', 'кебаб', 'фэй', 'кнр', 'чу', 'х', 'евв', 'кстати', 'шайба', 'зу', 'хах', 'шедевр', 'шея', 'июнь', 'виа', 'ум', 'г-жа', 'шлем', '-х', 'меморандум', 'инвалид', 'ты', 'из', 'зоя', 'прыщ', 'в', 'му', 'лойд', 'кедр', 'л', 'уж', 'де', 'км', 'пк', 'алонсо', 'тв', 'шья', 'лул', 'ггц', 'пума', 'боец', 'готч', 'ружьё', 'у', 'шляпа', 'хаггис', 'кг', 'ти', 'гусь', 'мл', 'ли-ми', 'э', 'для', 'сохо', 'зе-зе-з', 'даже', 'ив', 'щупальце', 'пёс', 'вьетнам', 'нв', 'ктк', 'псих', 'нба', 'ца', 'ндс', 'урумчи', 'йи', 'тху', 'з', 'гуш', 'ой', 'дауа', 'ир', 'мы', 'к', 'миун', 'дыра', 'сахар', 'ох', 'то', 'шилд', 'бюб', 'трюк', 'каосюн', 'осёл', 'аммо', 'вуз', 'дэл', 'няня', 'бюро', 'люжа', 'чи', 'п', 'хэбс', 'си', 'вацуп', 'орёл', 'юг', '-й', 'пюре', 'б', 'эс-пресс-ый', 'элм', 'тэд', 'веа', 'кетчуп', 'ещё', 'эм', 'кв', 'нм', 'вполне', 'офицер', 'йод', 'ку', 'азот', 'наш', 'тихий', '-', 'ааа', 'мг', 'вы', 'миф', 'сеул', 'на', 'апф', 'лён', 'иосиф', 'кешью', 'г', 'бо', 'паб', 'уэббер', 'но', 'шмидт', 'эу', 'лао-ш', 'ха', 'йо', 'сэр', 'мо', 'ухх', 'ма', 'мва', 'блузка', 'сянци', 'фельдшер', 'чунцин', 'ка', 'ян', 'вэ', '-я', 'я--', 'цех', 'ай', 'фэнтези', 'оуэн', 'плс', 'да', 'баффа', 'дядя', 'цацик', 'ву', 'ваш', 'фигня', 'всё', 'биг', 'по', 'фбр', 'р', 'пояс', 'егэ', 'бы', 'цюй', 'флирт', 'фуагра', 'ввс', 'двд', 'ил', 'и', 'эн', 'ло', 'нт', 'бф', 'ох-ох', 'кл', 'ям', 'гб', 'рмм', 'ушу', 'сын', 'ес', 'же', 'о', 'бруно', 'сабля', 'о-о', 'вяз', 'слр', 'эра', 'арнольд', 'сюй', 'аппетит', 'фи', 'сиэтл', 'кбр', 'го', 'оксид', 'ют', 'юнмэя', 'ин', 'чез', 'ит', 'ве', 'ху', 'пцк', 'овца', 'гвинея', 'боадицея', 'дыня', 'жюли', '-ю', 'изюм', 'ппп', 'миа', 'он', 'н', 'тысяча', 'уэйн', 'шлюха', 'ас', '-го', 'би', 'мм', 'лжец', 'мэм', 'ду', 'г-н', 'чоп', 'нут', '-ти', 'аубергин', 'хифя', 'тх', 'дуаньва', 'луч', 'мб', 'руфь', '-е', 'уас', 'ар', 'кай', 'ан', 'энрике', 'гнев', 'иначе', 'ци', 'шэн', 'шов', 'ши', 'ахиллесов', 'ф', 'мс', 'хм', 'гвоздь', 'ёкс', 'арпеджио', 'чувак', 'техно', 'цру', 'ла', 'лтд', 'за', 'чешуйка', 'пэм', 'пи', 'гс', 'тыл', 'тире', 'мясо', 'мп', 'кк', 'су', 'я', 'мяо', 'мао', 'ясли', 'в-', 'фу', 'кпк', 'хебес', 'ю', 'узел', 'чен', 'тётя', 'йо-йо', 'чоу', '-м', 'эх', 'язва', 'рич', 'пётр', 'ну', 'к-', 'яо', 'ввп', 'сяохуй', 'кесадилья', 'ни', 'е-а-к-и-н-с', 'гуччи', 'дуэт', 'эшли', 'пни', 'ээ', 'изъян', 'роща', 'хозяин', 'хэ', 'куи', 'эй', 'ми', 'оз', 'ос', 'йеч', 'ух', 'ввиду', 'ад', 'йон', 'яншао', 'упс'}

In [17]:
from collections import defaultdict


def find_shared_substrings(words, min_group_size=2, min_length=2):
    """
    Find all substrings that appear in at least `min_group_size` words.
    Only consider substrings of length >= min_length.
    """
    substring_map = defaultdict(set)  # substring -> set of words

    for word in words:
        n = len(word)
        seen = set()  # avoid counting duplicate substrings in the same word
        # Generate all substrings of length >= min_length
        for start in range(n):
            for end in range(start + min_length, n + 1):
                sub = word[start:end]
                if sub not in seen:
                    substring_map[sub].add(word)
                    seen.add(sub)

    # Filter by min_group_size
    result = [
        (sub, list(word_set))
        for sub, word_set in substring_map.items()
        if len(word_set) >= min_group_size
    ]

    # Optionally, sort by substring length (longest first)
    result.sort(key=lambda x: (-len(x[0]), x[0]))
    return result


# Example usage
words = df_words_ru_root.root

shared_subs = find_shared_substrings(words, min_group_size=2, min_length=2)

# Deduplicate shared_subs by group_words, keep longest sub
deduped = {}
for sub, group_words in shared_subs:
    key = tuple(sorted(group_words))  # make group_words hashable
    if key not in deduped or len(sub) > len(deduped[key]):
        deduped[key] = sub

# Rebuild as list of (sub, group_words)
shared_subs_deduped = {sub: list(key) for key, sub in deduped.items()}

print("Before deduplication:", len(shared_subs))
print("After deduplication:", len(shared_subs_deduped))
print("Deduplicated shared substrings:")
for sub, group_words in shared_subs_deduped.items():
    print(f"'{sub}' -> {group_words}")

Before deduplication: 54969
After deduplication: 22445
Deduplicated shared substrings:
'переквалифицировать' -> ['переквалифицировать', 'переквалифицироваться']
'неудовлетворительн' -> ['неудовлетворительно', 'неудовлетворительный']
'проконсультировать' -> ['проконсультировать', 'проконсультироваться']
'удовлетворительный' -> ['неудовлетворительный', 'удовлетворительный']
'администрирование' -> ['администрирование', 'бизнес-администрирование']
'высокотехнологичн' -> ['высокотехнологично', 'высокотехнологичный']
'идесятипроцентный' -> ['пятидесятипроцентный', 'семидесятипроцентный']
'исследовательский' -> ['исследовательский', 'научно-исследовательский']
'квалифицироваться' -> ['квалифицироваться', 'переквалифицироваться']
'конкурентоспособн' -> ['конкурентоспособность', 'конкурентоспособный']
'консультироваться' -> ['консультироваться', 'проконсультироваться']
'преподавательский' -> ['преподавательский', 'родительско-преподавательский']
'удовлетворительно' -> ['неудовлетворительно', 'удовлетворительно']
'удовлетворённость' -> ['неудовлетворённость', 'удовлетворённость']
'фотографироваться' -> ['сфотографироваться', 'фотографироваться']
'десятипроцентный' -> ['десятипроцентный', 'пятидесятипроцентный', 'семидесятипроцентный']
'зарегистрировать' -> ['зарегистрировать', 'зарегистрироваться']
'классифицировать' -> ['классифицировать', 'классифицироваться']
'коммуникационный' -> ['онлайн-коммуникационный', 'телекоммуникационный']
'профессиональный' -> ['непрофессиональный', 'профессиональный']
'регистрироваться' -> ['зарегистрироваться', 'регистрироваться']
'специализировать' -> ['специализировать', 'специализироваться']
'сфотографировать' -> ['сфотографировать', 'сфотографироваться']
'удовлетворительн' -> ['неудовлетворительно', 'неудовлетворительный', 'удовлетворительно', 'удовлетворительный']
'благотворительн' -> ['благотворительность', 'благотворительный']
'вашингтон-сквер' -> ['вашингтон-сквер', 'вашингтон-сквер-парк']
'восстанавливать' -> ['восстанавливать', 'восстанавливаться']
'демонстрировать' -> ['демонстрировать', 'демонстрироваться', 'продемонстрировать']
'доброжелательно' -> ['доброжелательно', 'недоброжелательно']
'еприготовленный' -> ['неприготовленный', 'свежеприготовленный']
'интервьюировать' -> ['интервьюировать', 'интервьюироваться']
'квалифицировать' -> ['дисквалифицировать', 'квалифицировать', 'квалифицироваться', 'переквалифицировать', 'переквалифицироваться']
'коллекционирова' -> ['коллекционирование', 'коллекционировать']
'консультировать' -> ['консультироваться', 'проконсультировать', 'проконсультироваться']
'континентальный' -> ['континентальный', 'межконтинентальный']
'конфиденциально' -> ['конфиденциально', 'конфиденциальность']
'ответственность' -> ['безответственность', 'ответственность']
'последовательно' -> ['непоследовательность', 'последовательно']
'предусматривать' -> ['предусматривать', 'предусматриваться']
'программировать' -> ['запрограммировать', 'программировать']
'телекоммуникаци' -> ['телекоммуникационный', 'телекоммуникация']
'фотографировать' -> ['сфотографировать', 'сфотографироваться', 'фотографировать', 'фотографироваться']
'-исследователь' -> ['научно-исследовательский', 'робот-исследователь', 'химик-исследователь']
'адцатиминутный' -> ['двадцатиминутный', 'пятнадцатиминутный']
'безответственн' -> ['безответственность', 'безответственный']
'вегетарианский' -> ['вегетарианский', 'невегетарианский']
'вительственный' -> ['покровительственный', 'правительственный']
'девяти-тридцат' -> ['девяти-тридцатить', 'девяти-тридцатый']
'действительный' -> ['действительный', 'недействительный']
'дисциплинирова' -> ['дисциплинирование', 'дисциплинировать']
'доброжелательн' -> ['доброжелательно', 'доброжелательный', 'недоброжелательно']
'заинтересовать' -> ['заинтересовать', 'заинтересоваться']
'интересоваться' -> ['заинтересоваться', 'интересоваться']
'комментировать' -> ['комментировать', 'прокомментировать']
'компетентность' -> ['компетентность', 'некомпетентность']
'кондиционирова' -> ['кондиционирование', 'кондиционировать']
'контролировать' -> ['контролировать', 'контролироваться']
'конфиденциальн' -> ['конфиденциально', 'конфиденциальность', 'конфиденциальный']
'корректировать' -> ['корректировать', 'скорректировать']
'мегапиксельный' -> ['-мегапиксельный', 'восьмимегапиксельный', 'мегапиксельный']
'мотивированный' -> ['мотивированный', 'мульти-мотивированный']
'непосредственн' -> ['непосредственно', 'непосредственный']
'онепроницаемый' -> ['влагонепроницаемый', 'водонепроницаемый']
'переворачивать' -> ['переворачивать', 'переворачиваться']
'перерабатывать' -> ['перерабатывать', 'перерабатываться']
'покровительств' -> ['покровительственный', 'покровительствовать']
'последовательн' -> ['непоследовательность', 'последовательно', 'последовательный']
'посредственный' -> ['непосредственный', 'посредственный']
'практиковаться' -> ['попрактиковаться', 'практиковаться']
'предпочтительн' -> ['предпочтительно', 'предпочтительный']
'приветствовать' -> ['поприветствовать', 'приветствовать', 'приветствоваться']
'привлекательно' -> ['привлекательно', 'привлекательность']
'профессиональн' -> ['непрофессиональный', 'профессионально', 'профессиональный']
'распространить' -> ['распространить', 'распространиться']
'расшифровывать' -> ['расшифровывать', 'расшифровываться']
'регистрировать' -> ['зарегистрировать', 'зарегистрироваться', 'регистрировать', 'регистрироваться']
'специализирова' -> ['специализированный', 'специализировать', 'специализироваться']
'справедливость' -> ['несправедливость', 'справедливость']
'станавливаться' -> ['восстанавливаться', 'останавливаться', 'устанавливаться']
'фантастический' -> ['научно-фантастический', 'фантастический']
'функциональный' -> ['многофункциональный', 'функциональный']
'экспортировать' -> ['реэкспортировать', 'экспортировать']
'электростанция' -> ['гидроэлектростанция', 'электростанция']
'-исследование' -> ['бизнес-исследование', 'онлайн-исследование']
'австралийский' -> ['австралийский', 'китайско-австралийский']
'автоматически' -> ['автоматически', 'автоматический']
'автотранспорт' -> ['автотранспорт', 'автотранспортный']
'анализировать' -> ['анализировать', 'проанализировать']
'балансировать' -> ['балансировать', 'сбалансировать']
'благоприятный' -> ['благоприятный', 'неблагоприятный']
'гарантировать' -> ['гарантировать', 'гарантироваться']
'действительно' -> ['действительно', 'действительность']
'дисконтирован' -> ['дисконтирование', 'дисконтированный']
'дискриминация' -> ['дискриминация', 'недискриминация']
'дцатиминутный' -> ['двадцатиминутный', 'пятнадцатиминутный', 'тридцатиминутный']
'зарезервирова' -> ['зарезервированный', 'зарезервировать']
'импортировать' -> ['импортировать', 'импортироваться']
'ина-сотрудник' -> ['женщина-сотрудник', 'мужчина-сотрудник']
'инвестировать' -> ['инвестировать', 'реинвестировать']
'индивидуально' -> ['индивидуально', 'индивидуальность']
'интервьюирова' -> ['интервьюирование', 'интервьюировать', 'интервьюироваться']
'интернет-банк' -> ['интернет-банк', 'интернет-банкинга', 'интернет-банковский']
'информировать' -> ['информировать', 'проинформировать']
'исследователь' -> ['исследователь', 'исследовательский', 'научно-исследовательский', 'робот-исследователь', 'химик-исследователь']
'ифицированный' -> ['высококвалифицированный', 'сертифицированный']
'ифицироваться' -> ['квалифицироваться', 'классифицироваться', 'переквалифицироваться']
'квалифицирова' -> ['высококвалифицированный', 'дисквалифицировать', 'квалифицировать', 'квалифицироваться', 'переквалифицировать', 'переквалифицироваться']
'кинематографи' -> ['кинематографист', 'кинематография']
'консультирова' -> ['консультирование', 'консультироваться', 'проконсультировать', 'проконсультироваться']
'копировальный' -> ['копировальный', 'фотокопировальный']
'корреспондент' -> ['банк-корреспондент', 'корреспондент']
'кционирование' -> ['коллекционирование', 'функционирование']
'меблированный' -> ['меблированный', 'немеблированный']
'монтироваться' -> ['монтироваться', 'ремонтироваться']
'нежелательный' -> ['нежелательный', 'спам-нежелательный']
'непростительн' -> ['непростительно', 'непростительный']
'нографический' -> ['порнографический', 'стенографический']
'оамериканский' -> ['афроамериканский', 'латиноамериканский']
'обслуживаться' -> ['обслуживаться', 'самообслуживаться']
'ографирование' -> ['стенографирование', 'фотографирование']
'онализировать' -> ['персонализировать', 'рационализировать']
'онлайн-торгов' -> ['онлайн-торговля', 'онлайн-торговый']
'ориентировать' -> ['ориентировать', 'ориентироваться']
'останавливать' -> ['останавливать', 'останавливаться']
'остроительный' -> ['машиностроительный', 'судостроительный']
'ответственный' -> ['безответственный', 'ответственный']
'подозрительно' -> ['подозрительно', 'подозрительность']
'подразделение' -> ['интернет-подразделение', 'подразделение']
'последователь' -> ['непоследовательность', 'последователь', 'последовательно', 'последовательный']
'предварительн' -> ['предварительно', 'предварительный']
'предоставлять' -> ['предоставлять', 'предоставляться']
'предсказуемый' -> ['непредсказуемый', 'предсказуемый']
'представитель' -> ['компания-представитель', 'представитель', 'представительный', 'представительство']
'преждевременн' -> ['преждевременно', 'преждевременный']
'преподаватель' -> ['преподаватель', 'преподавательский', 'родительско-преподавательский']
'приблизительн' -> ['приблизительно', 'приблизительный']
'привлекательн' -> ['привлекательно', 'привлекательность', 'привлекательный']
'программирова' -> ['запрограммировать', 'программирование', 'программировать']
'продолжительн' -> ['продолжительность', 'продолжительный']
'проектировать' -> ['перепроектировать', 'проектировать', 'спроектировать']
'производитель' -> ['производитель', 'производительность']
'противоположн' -> ['противоположность', 'противоположный']
'разрабатывать' -> ['разрабатывать', 'разрабатываться']
'рассматривать' -> ['рассматривать', 'рассматриваться']
'регулирование' -> ['регулирование', 'урегулирование']
'редактировать' -> ['отредактировать', 'редактировать']
'резервировать' -> ['зарезервировать', 'резервировать']
'рекламировать' -> ['рекламировать', 'рекламироваться']
'рекомендовать' -> ['зарекомендовать', 'порекомендовать', 'рекомендовать', 'рекомендоваться']
'ремонтировать' -> ['отремонтировать', 'ремонтировать', 'ремонтироваться']
'самообслужива' -> ['самообслуживание', 'самообслуживаться']
'самостоятельн' -> ['самостоятельно', 'самостоятельный']
'свидетельство' -> ['свидетельство', 'свидетельствовать']
'своевременный' -> ['несвоевременный', 'своевременный']
'сертифицирова' -> ['сертифицированный', 'сертифицировать']
'следовательно' -> ['непоследовательность', 'последовательно', 'следовательно']
'совершеннолет' -> ['несовершеннолетний', 'совершеннолетие']
'сосредоточить' -> ['сосредоточить', 'сосредоточиться']
'спользоваться' -> ['воспользоваться', 'использоваться']
'старшеклассни' -> ['старшеклассник', 'старшеклассница']
'ствительность' -> ['действительность', 'чувствительность']
'то-коричневый' -> ['золотисто-коричневый', 'красновато-коричневый']
'тоспособность' -> ['конкурентоспособность', 'кредитоспособность']
'транслировать' -> ['транслировать', 'транслироваться']
'тренироваться' -> ['потренироваться', 'тренироваться']
'устанавливать' -> ['устанавливать', 'устанавливаться']
'установленный' -> ['предустановленный', 'установленный']
'фантастически' -> ['научно-фантастический', 'фантастически', 'фантастический']
'финансировать' -> ['финансировать', 'финансироваться']
'формироваться' -> ['сформироваться', 'формироваться']
'фотографирова' -> ['сфотографировать', 'сфотографироваться', 'фотографирование', 'фотографировать', 'фотографироваться']
'функционирова' -> ['функционирование', 'функционировать']
'чувствительно' -> ['чувствительно', 'чувствительность']
'экономический' -> ['социально-экономический', 'экономический']
'ятидолларовый' -> ['десятидолларовый', 'пятидолларовый']
'ятипроцентный' -> ['десятипроцентный', 'пятидесятипроцентный', 'пятипроцентный', 'семидесятипроцентный']
'-департамент' -> ['бизнес-департамент', 'ит-департамент']
'-консультант' -> ['ит-консультант', 'фитнес-консультант']
'адаптировать' -> ['адаптировать', 'адаптироваться']
'американский' -> ['американский', 'афроамериканский', 'всеамериканский', 'китайско-американский', 'латиноамериканский', 'панамериканский']
'англоязычный' -> ['англоязычный', 'неанглоязычный']
'афроамерикан' -> ['афроамериканец', 'афроамериканский']
'балансирован' -> ['балансирование', 'сбалансированный']
'бизнес-контр' -> ['бизнес-контракт', 'бизнес-контроль']
'взаимодейств' -> ['взаимодействие', 'взаимодействовать']
'влекательный' -> ['привлекательный', 'развлекательный', 'увлекательный']
'внимательный' -> ['внимательный', 'невнимательный']
'возмутительн' -> ['возмутительно', 'возмутительный']
'возобновлять' -> ['возобновлять', 'возобновляться']
'ворачиваться' -> ['заворачиваться', 'отворачиваться', 'переворачиваться', 'поворачиваться', 'уворачиваться']
'восстановить' -> ['восстановить', 'восстановиться']
'восторженный' -> ['восторженный', 'невосторженный']
'восхитительн' -> ['восхитительно', 'восхитительный']
'дальновидный' -> ['дальновидный', 'недальновидный']
'действительн' -> ['действительно', 'действительность', 'действительный', 'недействительный']
'дисконтирова' -> ['дисконтирование', 'дисконтированный', 'дисконтировать']
'дополнительн' -> ['дополнительно', 'дополнительный']
'доставляться' -> ['доставляться', 'предоставляться']
'единовременн' -> ['единовременно', 'единовременный']
'единственный' -> ['единственный', 'один-единственный']
'ежеквартальн' -> ['ежеквартально', 'ежеквартальный']
'емонтировать' -> ['демонтировать', 'отремонтировать', 'ремонтировать', 'ремонтироваться']
'еологический' -> ['геологический', 'теологический']
'ервированный' -> ['зарезервированный', 'консервированный']
'ернизировать' -> ['вестернизировать', 'модернизировать']
'еспособность' -> ['жизнеспособность', 'платёжеспособность']
'естественный' -> ['естественный', 'неестественный']
'жизнеспособн' -> ['жизнеспособность', 'жизнеспособный']
'заворачивать' -> ['заворачивать', 'заворачиваться']
'заимствовать' -> ['заимствовать', 'позаимствовать']
'заинтересова' -> ['заинтересованный', 'заинтересовать', 'заинтересоваться']
'законодатель' -> ['законодательный', 'законодательство']
'значительный' -> ['значительный', 'незначительный']
'игнорировать' -> ['игнорировать', 'игнорироваться', 'проигнорировать']
'идентификаци' -> ['идентификационный', 'идентификация']
'индивидуальн' -> ['индивидуально', 'индивидуальность', 'индивидуальный']
'интеллектуал' -> ['интеллектуал', 'интеллектуальный']
'интересовать' -> ['заинтересовать', 'заинтересоваться', 'интересовать', 'интересоваться']
'иологический' -> ['биологический', 'физиологический']
'исключительн' -> ['исключительно', 'исключительный']
'использовать' -> ['использовать', 'использоваться']
'исследование' -> ['бизнес-исследование', 'исследование', 'онлайн-исследование']
'исторический' -> ['доисторический', 'исторический']
'ификационный' -> ['идентификационный', 'квалификационный']
'иционировать' -> ['кондиционировать', 'позиционировать']
'качественный' -> ['высококачественный', 'качественный', 'некачественный']
'ключительный' -> ['заключительный', 'исключительный']
'кологический' -> ['онкологический', 'экологический']
'коммерческий' -> ['коммерческий', 'некоммерческий']
'коммуникация' -> ['коммуникация', 'телекоммуникация']
'компетентный' -> ['компетентный', 'некомпетентный']
'конкурентный' -> ['высококонкурентный', 'конкурентный']
'консервативн' -> ['консервативно', 'консервативный']
'контрпредлож' -> ['контрпредложение', 'контрпредложить']
'корреспонден' -> ['банк-корреспондент', 'корреспондент', 'корреспонденция']
'кроэкономика' -> ['макроэкономика', 'микроэкономика']
'культивирова' -> ['культивированный', 'культивировать']
'кционировать' -> ['коллекционировать', 'функционировать']
'лизироваться' -> ['специализироваться', 'стабилизироваться']
'личественный' -> ['величественный', 'количественный']
'могательство' -> ['вымогательство', 'домогательство']
'нализировать' -> ['анализировать', 'персонализировать', 'проанализировать', 'рационализировать', 'сигнализировать']
'национальный' -> ['интернациональный', 'многонациональный', 'национальный', 'общенациональный', 'транснациональный']
'некомпетентн' -> ['некомпетентность', 'некомпетентный']
'необязательн' -> ['необязательно', 'необязательный']
'неопределённ' -> ['неопределённость', 'неопределённый']
'несправедлив' -> ['несправедливость', 'несправедливый']
'неудовлетвор' -> ['неудовлетворительно', 'неудовлетворительный', 'неудовлетворённость']
'нологический' -> ['технологический', 'хронологический']
'о-американск' -> ['китайско-американский', 'по-американск']
'о-коричневый' -> ['золотисто-коричневый', 'красновато-коричневый', 'светло-коричневый', 'тёмно-коричневый']
'обнаруживать' -> ['обнаруживать', 'обнаруживаться']
'обоснованный' -> ['необоснованный', 'обоснованный']
'обрабатывать' -> ['обрабатывать', 'обрабатываться']
'обслуживание' -> ['обслуживание', 'онлайн-обслуживание', 'самообслуживание']
'обязательный' -> ['необязательный', 'обязательный']
'ограниченный' -> ['неограниченный', 'ограниченный']
'ограничивать' -> ['ограничивать', 'ограничиваться']
'ографический' -> ['биографический', 'географический', 'демографический', 'порнографический', 'стенографический']
'одействовать' -> ['взаимодействовать', 'противодействовать', 'содействовать']
'ознакомиться' -> ['ознакомиться', 'познакомиться']
'ократический' -> ['аристократический', 'демократический']
'оплачиваемый' -> ['высокооплачиваемый', 'неоплачиваемый']
'определённый' -> ['неопределённый', 'определённый']
'организованн' -> ['организованность', 'организованный']
'организовать' -> ['организовать', 'организоваться']
'ористический' -> ['террористический', 'юмористический']
'ормироваться' -> ['нормироваться', 'сформироваться', 'формироваться']
'осторожность' -> ['неосторожность', 'осторожность', 'предосторожность']
'осуществлять' -> ['осуществлять', 'осуществляться']
'ответственно' -> ['безответственность', 'ответственно', 'ответственность', 'соответственно']
'очаровательн' -> ['очаровательно', 'очаровательный']
'очувствовать' -> ['почувствовать', 'сочувствовать']
'парикмахерск' -> ['парикмахерская', 'парикмахерский']
'первоначальн' -> ['первоначально', 'первоначальный']
'перемешивать' -> ['перемешивать', 'перемешиваться']
'поворачивать' -> ['поворачивать', 'поворачиваться']
'поддерживать' -> ['поддерживать', 'поддерживаться']
'подозрительн' -> ['подозрительно', 'подозрительность', 'подозрительный']
'подтверждать' -> ['подтверждать', 'подтверждаться']
'политический' -> ['космополитический', 'политический']
'полнительный' -> ['дополнительный', 'исполнительный']
'пользователь' -> ['многопользовательский', 'пользователь']
'пользоваться' -> ['воспользоваться', 'использоваться', 'пользоваться']
'посоветовать' -> ['посоветовать', 'посоветоваться']
'посредственн' -> ['непосредственно', 'непосредственный', 'посредственный']
'правительств' -> ['правительственный', 'правительство']
'практиковать' -> ['попрактиковаться', 'практиковать', 'практиковаться']
'предполагать' -> ['предполагать', 'предполагаться']
'предприимчив' -> ['предприимчивость', 'предприимчивый']
'председатель' -> ['председатель', 'председательствовать']
'представлять' -> ['представлять', 'представляться']
'припарковать' -> ['припарковать', 'припарковаться']
'приспособить' -> ['приспособить', 'приспособиться']
'прогнозирова' -> ['прогнозирование', 'прогнозировать']
'продовольств' -> ['продовольственный', 'продовольствие']
'продуктивный' -> ['контрпродуктивный', 'продуктивный']
'произведение' -> ['воспроизведение', 'произведение']
'пространство' -> ['киберпространство', 'пространство']
'профессионал' -> ['непрофессиональный', 'профессионал', 'профессионально', 'профессиональный']
'рабатываться' -> ['обрабатываться', 'перерабатываться', 'разрабатываться']
'распределять' -> ['распределять', 'распределяться']
'рассказывать' -> ['рассказывать', 'рассказываться']
'расстраивать' -> ['расстраивать', 'расстраиваться']

In [18]:
middle_groups = {
    sub: group_words
    for sub, group_words in shared_subs_deduped.items()
    if not group_words[0].startswith(sub) and not group_words[0].endswith(sub) and len(sub)>3
}
print(len(shared_subs_deduped))
print(len(middle_groups))
for sub, group_words in middle_groups.items():
    print(f"'{sub}' -> {group_words}")

22445
6272
'удовлетворительн' -> ['неудовлетворительно', 'неудовлетворительный', 'удовлетворительно', 'удовлетворительный']
'последовательно' -> ['непоследовательность', 'последовательно']
'-исследователь' -> ['научно-исследовательский', 'робот-исследователь', 'химик-исследователь']
'последовательн' -> ['непоследовательность', 'последовательно', 'последовательный']
'профессиональн' -> ['непрофессиональный', 'профессионально', 'профессиональный']
'квалифицирова' -> ['высококвалифицированный', 'дисквалифицировать', 'квалифицировать', 'квалифицироваться', 'переквалифицировать', 'переквалифицироваться']
'последователь' -> ['непоследовательность', 'последователь', 'последовательно', 'последовательный']
'программирова' -> ['запрограммировать', 'программирование', 'программировать']
'следовательно' -> ['непоследовательность', 'последовательно', 'следовательно']
'совершеннолет' -> ['несовершеннолетний', 'совершеннолетие']
'фантастически' -> ['научно-фантастический', 'фантастически', 'фантастический']
'фотографирова' -> ['сфотографировать', 'сфотографироваться', 'фотографирование', 'фотографировать', 'фотографироваться']
'корреспонден' -> ['банк-корреспондент', 'корреспондент', 'корреспонденция']
'о-американск' -> ['китайско-американский', 'по-американск']
'ответственно' -> ['безответственность', 'ответственно', 'ответственность', 'соответственно']
'пользователь' -> ['многопользовательский', 'пользователь']
'посредственн' -> ['непосредственно', 'непосредственный', 'посредственный']
'практиковать' -> ['попрактиковаться', 'практиковать', 'практиковаться']
'профессионал' -> ['непрофессиональный', 'профессионал', 'профессионально', 'профессиональный']
'резервирован' -> ['зарезервированный', 'резервирование']
'следовательн' -> ['непоследовательность', 'последовательно', 'последовательный', 'следовательно']
'удовлетворит' -> ['неудовлетворительно', 'неудовлетворительный', 'удовлетворительно', 'удовлетворительный', 'удовлетворить']
'функциональн' -> ['многофункциональный', 'типо-функционально', 'функциональный']
'илизировать' -> ['стабилизироваться', 'утилизировать']
'кологически' -> ['онкологический', 'экологически', 'экологический']
'мегапиксель' -> ['-мегапиксельный', 'восьмимегапиксельный', 'мегапиксель', 'мегапиксельный']
'определённо' -> ['неопределённость', 'определённо']
'оскользнуть' -> ['поскользнуться', 'проскользнуть']
'ответственн' -> ['безответственность', 'безответственный', 'ответственно', 'ответственность', 'ответственный', 'соответственно']
'политически' -> ['космополитический', 'политически', 'политический']
'приготовлен' -> ['неприготовленный', 'приготовление', 'свежеприготовленный']
'проектирова' -> ['перепроектировать', 'проектирование', 'проектировать', 'спроектировать']
'распределит' -> ['водораспределитель', 'распределить']
'редактирова' -> ['отредактировать', 'редактирование', 'редактировать']
'резервирова' -> ['зарезервированный', 'зарезервировать', 'резервирование', 'резервировать']
'своевременн' -> ['несвоевременный', 'своевременно', 'своевременный']
'спользовать' -> ['воспользоваться', 'использовать', 'использоваться']
'справедливо' -> ['несправедливость', 'справедливо', 'справедливость']
'творительно' -> ['благотворительность', 'неудовлетворительно', 'удовлетворительно']
'тренировать' -> ['потренироваться', 'тренировать', 'тренироваться']
'-исследова' -> ['бизнес-исследование', 'научно-исследовательский', 'онлайн-исследование', 'робот-исследователь', 'химик-исследователь']
'авительств' -> ['правительственный', 'правительство', 'представительство']
'вительство' -> ['покровительствовать', 'правительство', 'представительство']
'влекательн' -> ['привлекательно', 'привлекательность', 'привлекательный', 'развлекательный', 'увлекательно', 'увлекательный']
'говаривать' -> ['договариваться', 'отговаривать', 'разговаривать']
'интересова' -> ['заинтересованный', 'заинтересовать', 'заинтересоваться', 'интересовать', 'интересоваться']
'иссировать' -> ['плиссироваться', 'режиссировать']
'иционирова' -> ['кондиционирование', 'кондиционировать', 'позиционировать']
'ключительн' -> ['включительно', 'заключительный', 'исключительно', 'исключительный']
'кционирова' -> ['коллекционирование', 'коллекционировать', 'функционирование', 'функционировать']
'льствовать' -> ['довольствоваться', 'покровительствовать', 'председательствовать', 'свидетельствовать']
'матизирова' -> ['акклиматизироваться', 'ароматизированный']
'направленн' -> ['разнонаправленный', 'целенаправленно']
'национальн' -> ['интернациональный', 'многонациональный', 'национальность', 'национальный', 'общенациональный', 'транснациональный']
'о-китайски' -> ['англо-китайский', 'по-китайски']
'обязательн' -> ['необязательно', 'необязательный', 'обязательно', 'обязательный']
'ографирова' -> ['стенографирование', 'сфотографировать', 'сфотографироваться', 'фотографирование', 'фотографировать', 'фотографироваться']
'ологически' -> ['астрологический', 'биологический', 'геологический', 'метеорологический', 'онкологический', 'психологический', 'стоматологический', 'теологический', 'технологический', 'физиологический', 'хронологический', 'экологически', 'экологический']
'ообразован' -> ['высокообразованный', 'командообразование']
'ополнитель' -> ['дополнительно', 'дополнительный', 'пополнитель']
'определённ' -> ['неопределённость', 'неопределённый', 'определённо', 'определённый']
'организаци' -> ['дезорганизация', 'организационный', 'организация', 'реорганизация']
'планирован' -> ['незапланированный', 'планирование']
'полнительн' -> ['дополнительно', 'дополнительный', 'исполнительный']
'пользовать' -> ['воспользоваться', 'использовать', 'использоваться', 'пользоваться']
'последоват' -> ['непоследовательность', 'последователь', 'последовательно', 'последовательный', 'последовать']
'представит' -> ['компания-представитель', 'представитель', 'представительный', 'представительство', 'представить', 'представиться']
'продуктивн' -> ['контрпродуктивный', 'продуктивность', 'продуктивный']
'производит' -> ['воспроизводить', 'производитель', 'производительность', 'производить', 'производиться']
'реалистичн' -> ['нереалистичный', 'реалистично', 'реалистичный', 'сюрреалистичный']
'регулирова' -> ['отрегулировать', 'регулирование', 'регулировать', 'регулироваться', 'урегулирование', 'урегулировать']
'совершенно' -> ['несовершеннолетний', 'совершенно', 'совершеннолетие']
'соответств' -> ['несоответствие', 'соответственно', 'соответствие', 'соответствовать', 'соответствующий']
'справедлив' -> ['несправедливость', 'несправедливый', 'справедливо', 'справедливость', 'справедливый']
'творительн' -> ['благотворительность', 'благотворительный', 'неудовлетворительно', 'неудовлетворительный', 'удовлетворительно', 'удовлетворительный']
'технически' -> ['сантехнический', 'технически', 'технический']
'технологич' -> ['высокотехнологично', 'высокотехнологичный', 'технологический']
'тизировать' -> ['акклиматизироваться', 'маршрутизировать']
'тифицирова' -> ['идентифицировать', 'сертифицированный', 'сертифицировать']
'удивительн' -> ['неудивительный', 'удивительно', 'удивительный']
'удовлетвор' -> ['неудовлетворительно', 'неудовлетворительный', 'неудовлетворённость', 'удовлетворение', 'удовлетворительно', 'удовлетворительный', 'удовлетворить', 'удовлетворять', 'удовлетворённость']
'установлен' -> ['предустановленный', 'установление', 'установленный']
'формулиров' -> ['сформулировать', 'формулировка']
'юридически' -> ['параюридический', 'юридически', 'юридический']
'азировать' -> ['базироваться', 'газировать', 'перефразировать']
'ализирова' -> ['анализировать', 'госпитализировать', 'детализировать', 'персонализировать', 'проанализировать', 'рационализировать', 'сигнализировать', 'специализированный', 'специализировать', 'специализироваться']
'ансирован' -> ['балансирование', 'сбалансированный', 'финансирование']
'астически' -> ['гимнастический', 'научно-фантастический', 'пластический', 'саркастический', 'фантастически', 'фантастический']
'варительн' -> ['пищеварительный', 'предварительно', 'предварительный']
'ветственн' -> ['безответственность', 'безответственный', 'ответственно', 'ответственность', 'ответственный', 'приветственный', 'соответственно']
'вительств' -> ['покровительственный', 'покровительствовать', 'правительственный', 'правительство', 'представительство']
'водительн' -> ['производительность', 'сопроводительный']
'графирова' -> ['стенографирование', 'сфотографировать', 'сфотографироваться', 'телеграфировать', 'фотографирование', 'фотографировать', 'фотографироваться']
'держивать' -> ['воздерживаться', 'выдерживать', 'задерживать', 'задерживаться', 'поддерживать', 'поддерживаться', 'придерживаться', 'сдерживать', 'удерживать', 'удерживаться']
'ептически' -> ['антисептический', 'скептически', 'эпилептический']
'ервирован' -> ['зарезервированный', 'консервированный', 'резервирование']
'желательн' -> ['доброжелательно', 'доброжелательный', 'желательно', 'желательный', 'недоброжелательно', 'нежелательный', 'спам-нежелательный']
'изировать' -> ['акклиматизироваться', 'активизировать', 'анализировать', 'вестернизировать', 'госпитализировать', 'детализировать', 'максимизировать', 'маршрутизировать', 'механизировать', 'минимизировать', 'модернизировать', 'монополизировать', 'персонализировать', 'популяризировать', 'проанализировать', 'рационализировать', 'сигнализировать', 'символизировать', 'специализировать', 'специализироваться', 'стабилизироваться', 'утилизировать']
'исследова' -> ['бизнес-исследование', 'исследование', 'исследователь', 'исследовательский', 'исследовать', 'научно-исследовательский', 'онлайн-исследование', 'робот-исследователь', 'химик-исследователь']
'истрирова' -> ['администрирование', 'бизнес-администрирование', 'зарегистрировать', 'зарегистрироваться', 'регистрировать', 'регистрироваться']
'ифицирова' -> ['высококвалифицированный', 'диверсифицировать', 'дисквалифицировать', 'идентифицировать', 'квалифицировать', 'квалифицироваться', 'классифицировать', 'классифицироваться', 'переквалифицировать', 'переквалифицироваться', 'сертифицированный', 'сертифицировать']
'компьютер' -> ['инженер-компьютерщик', 'компьютер', 'компьютеризированный', 'компьютерный', 'компьютерс']
'конкурент' -> ['высококонкурентный', 'конкурент', 'конкурентный', 'конкурентоспособность', 'конкурентоспособный']
'консульта' -> ['ит-консультант', 'консультант', 'консультативный', 'консультационный', 'консультация', 'фитнес-консультант']
'литически' -> ['аналитический', 'космополитический', 'политически', 'политический']
'логически' -> ['астрологический', 'биологический', 'геологический', 'логический', 'метеорологический', 'онкологический', 'психологический', 'стоматологический', 'теологический', 'технологический', 'физиологический', 'хронологический', 'экологически', 'экологический']
'ментирова' -> ['документирование', 'комментировать', 'прокомментировать']
'мечательн' -> ['достопримечательность', 'замечательный']
'музыкальн' -> ['мини-музыкальный', 'музыкальность', 'музыкальный']
'натуральн' -> ['-натуральный', 'натурально', 'натуральный']
'неспособн' -> ['жизнеспособность', 'жизнеспособный', 'неспособный']
'новременн' -> ['единовременно', 'единовременный', 'одновременно', 'одновременный']
'оамерикан' -> ['афроамериканец', 'афроамериканский', 'латиноамериканский']
'образован' -> ['бизнес-образование', 'высокообразованный', 'командообразование', 'образование']
'обязатель' -> ['необязательно', 'необязательный', 'обязательно', 'обязательный', 'обязательство']
'овательно' -> ['непоследовательность', 'очаровательно', 'последовательно', 'следовательно', 'требовательно']
'оговорить' -> ['договориться', 'оговориться', 'поговорить']
'ограничен' -> ['неограниченный', 'ограничение', 'ограниченный']
'одительск' -> ['водительский', 'родительский', 'родительско-преподавательский']
'оиндустри' -> ['высокоиндустриальный', 'киноиндустрия']
'оказатель' -> ['доказательство', 'показатель']
'орекоменд' -> ['порекомендовать', 'саморекомендация']
'осторожно' -> ['неосторожность', 'осторожно', 'осторожность', 'предосторожность']
'официальн' -> ['неофициальный', 'официально', 'официальный']
'охозяйств' -> ['домохозяйство', 'сельскохозяйственный']
'планирова' -> ['запланировать', 'незапланированный', 'планирование', 'планировать', 'планироваться', 'спланировать']
'полнитель' -> ['дополнительно', 'дополнительный', 'исполнительный', 'пополнитель']
'пользован' -> ['использование', 'неиспользованный', 'пользование']
'пользоват' -> ['воспользоваться', 'использовать', 'использоваться', 'многопользовательский', 'пользователь', 'пользоваться']
'посредств' -> ['непосредственно', 'непосредственный', 'посредственный', 'посредством']
'празднова' -> ['отпраздновать', 'празднование', 'праздновать', 'праздноваться']
'приветств' -> ['поприветствовать', 'приветственный', 'приветствие', 'приветствовать', 'приветствоваться']
'проводник' -> ['полупроводниковый', 'проводник']
'программи' -> ['запрограммировать', 'программирование', 'программировать', 'программист']
'разительн' -> ['выразительный', 'изобразительный', 'поразительно', 'поразительный']
'распредел' -> ['водораспределитель', 'распределение', 'распределить', 'распределять', 'распределяться']
'семнадцат' -> ['восемнадцатый', 'восемнадцать', 'семнадцатый', 'семнадцать']
'сказывать' -> ['высказываться', 'предсказывать', 'рассказывать', 'рассказываться']
'совершенн' -> ['несовершеннолетний', 'совершенно', 'совершеннолетие', 'совершенный']
'соединить' -> ['воссоединиться', 'подсоединить', 'присоединиться', 'соединить']
'соединять' -> ['присоединяться', 'соединять', 'соединяться']
'спокойств' -> ['беспокойство', 'спокойствие']
'спользова' -> ['воспользоваться', 'использование', 'использовать', 'использоваться', 'неиспользованный']
'спортиров' -> ['реэкспортировать', 'транспортировка', 'экспортировать']
'сследоват' -> ['исследователь', 'исследовательский', 'исследовать', 'научно-исследовательский', 'расследовать', 'робот-исследователь', 'химик-исследователь']
'стандартн' -> ['нестандартно', 'нестандартный', 'стандартно', 'стандартный']
'становлен' -> ['восстановление', 'постановление', 'предустановленный', 'становление', 'установление', 'установленный']
'ствительн' -> ['действительно', 'действительность', 'действительный', 'недействительный', 'чувствительно', 'чувствительность', 'чувствительный']
'стоятельн' -> ['настоятельно', 'самостоятельно', 'самостоятельный']
'страивать' -> ['выстраиваться', 'настраивать', 'настраиваться', 'расстраивать', 'расстраиваться', 'устраивать', 'устраиваться']
'счастливи' -> ['посчастливиться', 'счастливица']
'творитель' -> ['благотворительность', 'благотворительный', 'неудовлетворительно', 'неудовлетворительный', 'растворитель', 'удовлетворительно', 'удовлетворительный']
'тестирова' -> ['протестировать', 'тестирование', 'тестировать', 'тестироваться']
'технологи' -> ['высокотехнологично', 'высокотехнологичный', 'политтехнология', 'технологический', 'технология']
'торговать' -> ['поторговаться', 'торговать', 'торговаться']
'тоспособн' -> ['конкурентоспособность', 'конкурентоспособный', 'кредитоспособность', 'работоспособный']
'ужественн' -> ['дружественно', 'дружественный', 'мужественно', 'мужественный']
'ультативн' -> ['консультативный', 'результативность', 'факультативный']
'фантастич' -> ['научно-фантастический', 'фантастически', 'фантастический', 'фантастично']
'формирова' -> ['информировать', 'проинформировать', 'реформировать', 'сформировать', 'сформироваться', 'формирование', 'формировать', 'формироваться']
'фотографи' -> ['сфотографировать', 'сфотографироваться', 'фотографирование', 'фотографировать', 'фотографироваться', 'фотография']
'ционально' -> ['национальность', 'типо-функционально', 'эмоционально']
'ционирова' -> ['коллекционирование', 'коллекционировать', 'кондиционирование', 'кондиционировать', 'позиционировать', 'функционирование', 'функционировать']
'человечес' -> ['по-человечески', 'человеческий', 'человечество']
'-банкинг' -> ['интернет-банкинга', 'онлайн-банкинг']
'-работни' -> ['бизнес-работник', 'женщина-работница']
'-тридцат' -> ['девяти-тридцатить', 'девяти-тридцатый', 'семь-тридцать', 'четыре-тридцать']
'-фантаст' -> ['научно-фантастический', 'писатель-фантаст']
'ажительн' -> ['раздражительный', 'уважительно']
'алистичн' -> ['индивидуалистичный', 'нереалистичный', 'реалистично', 'реалистичный', 'сюрреалистичный']
'анирован' -> ['незапланированный', 'планирование', 'сканирование']
'ансирова' -> ['балансирование', 'балансировать', 'сбалансированный', 'сбалансировать', 'финансирование', 'финансировать', 'финансироваться']
'асительн' -> ['пригласительный', 'спасительница']
'биографи' -> ['автобиография', 'биографический', 'биография']
'блирован' -> ['дублирование', 'меблированный', 'немеблированный']
'блокиров' -> ['антиблокировочный', 'блокирование', 'блокировщик', 'заблокировать']
'бъективн' -> ['объективно', 'объективность', 'объективный', 'субъективный']
'варивать' -> ['договариваться', 'отговаривать', 'переваривать', 'разговаривать']
'воритель' -> ['благотворительность', 'благотворительный', 'громкоговоритель', 'неудовлетворительно', 'неудовлетворительный', 'растворитель', 'удовлетворительно', 'удовлетворительный']
'вязывать' -> ['ввязываться', 'завязывать', 'навязывать', 'привязываться', 'связывать', 'связываться']
'гательно' -> ['прилагательное', 'трогательно']
'готворит' -> ['благотворительность', 'благотворительный', 'боготворить']
'готовлен' -> ['изготовление', 'неприготовленный', 'приготовление', 'свежеприготовленный']
'грессивн' -> ['агрессивность', 'агрессивный', 'прогрессивный']
'дительно' -> ['бдительность', 'производительность', 'убедительно']
'евозможн' -> ['всевозможный', 'невозможно', 'невозможный']
'евременн' -> ['несвоевременный', 'преждевременно', 'преждевременный', 'своевременно', 'своевременный']
'едственн' -> ['непосредственно', 'непосредственный', 'посредственный', 'следственный']
'ектирова' -> ['корректировать', 'перепроектировать', 'проектирование', 'проектировать', 'скорректировать', 'спроектировать']
'ентирова' -> ['документирование', 'комментировать', 'ориентировать', 'ориентироваться', 'прокомментировать']
'енциальн' -> ['конфиденциально', 'конфиденциальность', 'конфиденциальный', 'потенциально', 'потенциальный', 'преференциальный']
'ервирова' -> ['зарезервированный', 'зарезервировать', 'консервированный', 'резервирование', 'резервировать']
'еспособн' -> ['жизнеспособность', 'жизнеспособный', 'неспособный', 'платёжеспособность']
'естирова' -> ['инвестирование', 'инвестировать', 'протестировать', 'реинвестировать', 'тестирование', 'тестировать', 'тестироваться']
'жественн' -> ['дружественно', 'дружественный', 'мужественно', 'мужественный', 'невежественно', 'торжественный', 'художественно', 'художественный']
'звлекать' -> ['извлекаться', 'развлекать', 'развлекаться']
'зировать' -> ['акклиматизироваться', 'активизировать', 'анализировать', 'базироваться', 'вестернизировать', 'газировать', 'госпитализировать', 'детализировать', 'максимизировать', 'маршрутизировать', 'механизировать', 'минимизировать', 'модернизировать', 'монополизировать', 'перефразировать', 'персонализировать', 'позировать', 'популяризировать', 'проанализировать', 'прогнозировать', 'рационализировать', 'сигнализировать', 'символизировать', 'специализировать', 'специализироваться', 'стабилизироваться', 'утилизировать']
'знательн' -> ['подсознательный', 'признательность', 'признательный']
'зователь' -> ['многопользовательский', 'образовательный', 'пользователь']
'изительн' -> ['приблизительно', 'приблизительный', 'унизительно']
'изованно' -> ['организованность', 'централизованно']
'индустри' -> ['-индустрия', 'высокоиндустриальный', 'индустрия', 'ит-индустрия', 'киноиндустрия']
'инирован' -> ['дисциплинирование', 'комбинированный']
'инственн' -> ['воинственно', 'единственный', 'один-единственный', 'таинственный']
'ионально' -> ['национальность', 'профессионально', 'типо-функционально', 'эмоционально']
'ительств' -> ['жительство', 'местожительство', 'покровительственный', 'покровительствовать', 'поручительство', 'правительственный', 'правительство', 'представительство', 'совместительство', 'строительство']